package frontend

import (
	"embed"
	"io/fs"
	"net/http"
	"strings"
)

// The all: prefix also embeds the chunks starting with _ generated by Vite.
//
//go:embed all:dist
var assets embed.FS

// Handler serves the bundled frontend, including Vue Router's base pages.
func Handler() http.Handler {
	dist, err := fs.Sub(assets, "dist")
	if err != nil {
		panic(err)
	}

	files := http.FileServer(http.FS(dist))

	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet && r.Method != http.MethodHead {
			http.NotFound(w, r)
			return
		}

		// Vue Router keeps this document's policy when navigating to a public link.
		w.Header().Set("Referrer-Policy", "no-referrer")

		if isAppRoute(r.URL.Path) {
			if strings.HasPrefix(r.URL.Path, "/base/") || strings.HasPrefix(r.URL.Path, "/share/") {
				w.Header().Set("X-Robots-Tag", "noindex, nofollow")
			}

			r = r.Clone(r.Context())
			r.URL.Path = "/"
		}

		files.ServeHTTP(w, r)
	})
}

// isAppRoute reports whether the path is a Vue Router page that serves index.html.
func isAppRoute(path string) bool {
	switch path {
	case "/login", "/register", "/settings", "/admin":
		return true
	}
	for _, prefix := range []string{"/base/", "/share/", "/settings/", "/admin/"} {
		if strings.HasPrefix(path, prefix) {
			return true
		}
	}
	return false
}
