master:
  push:
    - name: "构建镜像"
      services:
        - docker
      docker:
        image: docker.cnb.cool/nekobase/base-images/golang-1.22:latest
        volumes:
          - /go/pkg/mod
          - /root/.cache/go-build
      stages:
        - name: 设置镜像 tag
          script: echo -n "${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:$(date -u '+%Y%m%d-%H%M%S')"
          exports:
            info: IMAGE_TAG

        - name: 编译 Go + 构建镜像 + 推送镜像
          script: |
            go build -v -trimpath -ldflags "-w -s -extldflags '-static' -X 'github.com/wuhan005/sayrud/internal/appconst.BuildCommit=$GITHUB_SHA'" -o sayrud-server ./cmd/sayrud-server
            docker build -t $IMAGE_TAG .
            docker push $IMAGE_TAG