master:
  push:
    - name: "构建镜像"
      services:
        - docker
      docker:
        image: golang:1.22
        volumes:
          - /go/pkg/mod
          - /root/.cache/go-build
      stages:
        - name: 设置镜像 tag
          script: echo -n "${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:$(date -u '+%Y%m%d-%H%M%S')"
          exports:
            info: IMAGE_TAG

        - name: Go mod download
          script: go mod download

        - name: 编译 Go
          script: go build -v -trimpath -ldflags "-w -s -extldflags '-static' -X 'github.com/wuhan005/sayrud/internal/appconst.BuildCommit=$GITHUB_SHA'" -o sayrud-server ./cmd/sayrud-server

        - name: 构建镜像
          script: docker build -t $IMAGE_TAG .

        - name: 推送镜像
          script: docker push $IMAGE_TAG