/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/*
 * ---------------------------------------------------------------
 * ## THIS FILE WAS GENERATED VIA SWAGGER-TYPESCRIPT-API        ##
 * ##                                                           ##
 * ## AUTHOR: acacode                                           ##
 * ## SOURCE: https://github.com/acacode/swagger-typescript-api ##
 * ---------------------------------------------------------------
 */

export interface AIAdvice {
  action: "tables";
  messages: AIMessage[];
}

export interface AIAdviceResp {
  action: string;
  /** ActionJSON is the structured payload of the action, which can be passed to the apply API as is. */
  actionJson: object;
  description: string;
  /** Raw is the raw output of the model. */
  raw: string;
}

export interface AIApply {
  action: "tables";
  /** ActionJson is the actionJson returned by the advice API. */
  actionJson: object;
}

export interface AIMessage {
  content: string;
  role: string;
}

export interface Action {
  /** Action is the type of the action. */
  action:
    | "record.add"
    | "record.set"
    | "record.delete"
    | "field.add"
    | "field.set"
    | "field.setType"
    | "field.setShortcut"
    | "field.move"
    | "field.delete"
    | "view.add"
    | "view.set"
    | "view.move"
    | "view.delete"
    | "table.dirty";
  /** Dirty is the data to reload for table.dirty. */
  dirty?: DirtyScope;
  /** Field is the field properties for field.add / field.set / field.setType. */
  field?: FieldAttrs;
  /** FieldUID is generated by the client for field.add. */
  fieldUID?: string;
  /** Index is the zero-based position for field.move / view.move, and the optional insert position for field.add / view.add. */
  index?: number;
  /** KeepValues skips regenerating the existing cells when field.add / field.setShortcut sets a shortcut, e.g. duplicating a table. */
  keepValues?: boolean;
  /** RecordUID is generated by the client for record.add. */
  recordUID?: string;
  /** RecordUIDs are the records to delete for record.delete. */
  recordUIDs?: string[];
  /** Shortcut is the new shortcut for field.setShortcut, null removes the shortcut. */
  shortcut?: FieldShortcut;
  /** Values are the cell values keyed by field UID for record.add / record.set, a null value clears the cell. */
  values?: Record<string, any>;
  /** View is the view properties for view.add / view.set. */
  view?: ViewAttrs;
  /** ViewUID is generated by the client for view.add. */
  viewUID?: string;
}

export interface AddProjectMember {
  email: string;
  role: "manager" | "editor" | "viewer";
}

export interface AdminAISettings {
  /** APIKeySet reports whether an API key is saved and readable. */
  apiKeySet: boolean;
  /** BaseURL is the API root including the version, e.g. https://api.openai.com/v1. */
  baseURL: string;
  /** Enabled reports whether the global AI model is enabled. */
  enabled: boolean;
  /** Model is the name of the model to call. */
  model: string;
  /** SecretsReady is false if auth.secret_key is not configured, the API key can not be saved. */
  secretsReady: boolean;
  /** TimeoutSeconds is the timeout of a completion request. */
  timeoutSeconds: number;
}

export interface AdminAuthProvider {
  acsURL: string;
  allowedEmailDomains: string[];
  allowedGroups: string[];
  autoCreateUser: boolean;
  /** CallbackURL, ACSURL and MetadataURL are filled in at the identity provider, empty if the external URL is not set. */
  callbackURL: string;
  config: AuthProviderConfig;
  createdAt: string;
  enabled: boolean;
  hasBindPassword: boolean;
  /** HasClientSecret and HasBindPassword report whether the secrets have been saved. */
  hasClientSecret: boolean;
  icon: string;
  id: number;
  /** IdentityCount is the number of users bound to the sign-in method. */
  identityCount: number;
  linkByEmail: boolean;
  metadataURL: string;
  name: string;
  position: number;
  slug: string;
  type: "oauth2" | "oidc" | "saml" | "ldap";
  updatedAt: string;
}

export interface AdminCreateUser {
  email: string;
  isAdmin: boolean;
  password: string;
  userName: string;
}

export interface AdminCredential {
  hasValue: boolean;
  key: string;
  name?: string;
  type: "bearer" | "header" | "query";
}

export interface AdminFieldShortcut {
  /** Code defines `async function execute(params, context)` returning the cell value. */
  code: string;
  /** CreatedAt is the time the shortcut was created. */
  createdAt: string;
  /** Credentials are the credentials the script can use when fetching. */
  credentials: AdminCredential[];
  /** Description tells the members what the shortcut does. */
  description: string;
  /** Domains are the hosts the script can fetch, including their subdomains. */
  domains: string[];
  /** Enabled reports whether the members can attach and execute the shortcut. */
  enabled: boolean;
  /** FormItems are the inputs configured in the field editor and passed to execute as the params. */
  formItems: ShortcutFormItem[];
  /** Name is shown in the field editor. */
  name: string;
  /** ResultType is the type of the fields the shortcut can be attached to. */
  resultType: string;
  /** TimeoutSeconds is the time limit of an execution. */
  timeoutSeconds: number;
  /** UID is the identifier the fields refer to the shortcut by. */
  uid: string;
  /** UpdatedAt is the time the shortcut was last updated. */
  updatedAt: string;
  /** UsedBy is the number of the fields using the shortcut. */
  usedBy: number;
}

export interface AdminOverview {
  activeSessions: number;
  projects: number;
  recentUsers: AdminUser[];
  records: number;
  system: AdminSystemInfo;
  tables: number;
  users: AdminUserStats;
}

export interface AdminProject {
  createdAt: string;
  /** MemberCount is the number of collaborators, excluding the owner. */
  memberCount: number;
  name: string;
  owner: UserBrief;
  tableCount: number;
  uid: string;
}

export interface AdminResetPassword {
  password: string;
}

export interface AdminSetUserAdmin {
  isAdmin: boolean;
}

export interface AdminSetUserStatus {
  disabled: boolean;
}

export interface AdminSystemInfo {
  buildCommit: string;
  goVersion: string;
  settings: SystemSettings;
}

export interface AdminTransferProject {
  userID: number;
}

export interface AdminUpdateUser {
  userName: string;
}

export interface AdminUser {
  color: string;
  createdAt: string;
  disabled: boolean;
  email: string;
  emailMd5: string;
  id: number;
  isAdmin: boolean;
  lastSignInAt: string;
  ownedProjectCount: number;
  /** Providers are the sign-in methods bound by the user. */
  providers: AuthProviderBrief[];
  userName: string;
}

export interface AdminUserStats {
  admins: number;
  disabled: number;
  newLast7Days: number;
  total: number;
}

export interface AuthProviderBrief {
  icon: string;
  name: string;
  slug: string;
}

export interface AuthProviderConfig {
  allowIdPInitiated?: boolean;
  /** AuthURL, TokenURL and UserInfoURL are the authorization, token and user info URLs of OAuth 2.0. */
  authURL?: string;
  baseDN?: string;
  /** BindDN is the service account to search the users, it binds anonymously if empty. */
  bindDN?: string;
  /** ClientID and Scopes are used by OAuth 2.0 and OIDC. */
  clientID?: string;
  /** EmailAttribute, NameAttribute and GroupsAttribute are the attribute names of SAML or LDAP, the common SAML attributes are detected if empty. */
  emailAttribute?: string;
  emailPath?: string;
  /** EmailsURL returns [{email, primary, verified}], the primary and verified email in it takes precedence if set (GitHub, Gitea). */
  emailsURL?: string;
  groupsAttribute?: string;
  groupsClaim?: string;
  groupsPath?: string;
  /** IdPMetadataURL or IdPMetadataXML is the metadata of the SAML IdP, only one of them is set. */
  idpMetadataURL?: string;
  idpMetadataXML?: string;
  /** Issuer is the OIDC issuer for discovery. */
  issuer?: string;
  nameAttribute?: string;
  nameClaim?: string;
  namePath?: string;
  /** RootCA is the CA in PEM to verify the LDAP server certificate, the system CAs are used if empty. */
  rootCA?: string;
  scopes?: string[];
  /** SPCertificate is the generated SP certificate in PEM, the private key is in Secrets. */
  spCertificate?: string;
  startTLS?: boolean;
  subjectAttribute?: string;
  /** SubjectPath, EmailPath, NamePath and GroupsPath are the dot paths in the user info JSON, e.g. data.user.email. */
  subjectPath?: string;
  tokenURL?: string;
  /** TrustEmail treats the email from the IdP as verified, OIDC uses email_verified instead. */
  trustEmail?: boolean;
  /** URL is the LDAP server address, ldap:// or ldaps://. */
  url?: string;
  /** The {username} in UserFilter is replaced with the escaped user name of the sign-in. */
  userFilter?: string;
  userInfoURL?: string;
}

export interface BatchCreateRecords {
  /** Data is the list of cell values keyed by field UID, one item for each record. */
  data: Record<string, any>[];
}

export interface Changeset {
  /** ClientID is the connection that submits the changeset, it is empty for the changesets generated by the server. */
  clientId: string;
  operations: Operation[];
  rev: number;
  /** Signature is generated by the submitting client to recognize its own changeset, it is empty for the changesets generated by the server. */
  signature: string;
  tableUID: string;
}

export interface CreateAuthProvider {
  allowedEmailDomains: string[];
  allowedGroups: string[];
  autoCreateUser: boolean;
  /** BindPassword is the password of the LDAP service account, empty keeps the saved one when updating. */
  bindPassword?: string;
  /** ClientSecret is the client secret of OAuth 2.0 or OIDC, empty keeps the saved one when updating. */
  clientSecret?: string;
  config: AuthProviderConfig;
  enabled: boolean;
  icon: string;
  linkByEmail: boolean;
  name: string;
  /** Slug is part of the callback URL and can not be changed after creating. */
  slug: string;
  type: "oauth2" | "oidc" | "saml" | "ldap";
}

export interface CreateField {
  label: string;
  /** Metadata is the type-specific configuration, e.g. select options or the formula expression. */
  metadata?: Record<string, any>;
  type:
    | "text"
    | "single_select"
    | "multi_select"
    | "datetime"
    | "number"
    | "checkbox"
    | "formula";
}

export interface CreateFields {
  fields: CreateField[];
}

export interface CreateProject {
  name: string;
}

export interface CreateRecord {
  /** Data is the cell values keyed by field UID. */
  data?: Record<string, any>;
}

export interface CreateTable {
  name: string;
}

export interface DeleteAccount {
  /** ConfirmEmail is the own email entered by users without a password. */
  confirmEmail?: string;
  /** Password is the current password of users with one. */
  password?: string;
}

export interface DirtyScope {
  allRecords?: boolean;
  fields?: boolean;
  records?: string[];
  views?: boolean;
}

export interface FetchRecords {
  uids: string[];
}

export interface FieldAttrs {
  /** Label is the title of the field. */
  label?: string;
  /** Metadata is the type-specific configuration, e.g. select options or the formula expression. */
  metadata?: Record<string, any>;
  /** Shortcut is the optional shortcut of the new field for field.add. */
  shortcut?: FieldShortcut;
  /** Type is the type of the field, the values are converted for field.setType. */
  type?:
    | "text"
    | "single_select"
    | "multi_select"
    | "datetime"
    | "number"
    | "checkbox"
    | "formula";
}

export interface FieldShortcut {
  /** AutoUpdate regenerates the cell when any referenced field of the record changes. */
  autoUpdate: boolean;
  /** ID is the UID of a custom shortcut. */
  id: string;
  /**
   * Inputs are the configured values keyed by the form item key, a field_select item stores the field UID,
   * and a prompt item stores the text referencing the fields by `{fieldUID}`.
   */
  inputs: Record<string, any>;
}

export interface FieldShortcutManifest {
  /** Available is false if the shortcut is disabled. */
  available: boolean;
  /** Description tells what the shortcut does. */
  description: string;
  /** FormItems are the inputs to configure in the field editor. */
  formItems: ShortcutFormItem[];
  /** ID is the UID of a custom shortcut. */
  id: string;
  /** Kind is how the shortcut is executed, by a custom script. */
  kind: "script";
  /** Name is shown in the field editor. */
  name: string;
  /** ResultTypes are the types of the fields the shortcut can be attached to. */
  resultTypes: string[];
}

export interface LDAPSignIn {
  password: string;
  username: string;
}

export interface ListAdminAuthProvidersResp {
  externalURL: string;
  providers: AdminAuthProvider[];
  /** SecretsReady reports whether auth.secret_key is configured. */
  secretsReady: boolean;
}

export interface ListAdminProjectsResp {
  projects: AdminProject[];
  total: number;
}

export interface ListAdminUsersResp {
  total: number;
  users: AdminUser[];
}

export interface ListChangesetsResp {
  changesets: Changeset[];
  /** HasMore reports there are more changesets after the last one, the client should fetch again from its revision. */
  hasMore: boolean;
}

export interface ListProjectsResp {
  projects: ProjectListItem[];
  total: number;
}

export interface ListRecordsResp {
  records: SLRecord[];
  /** Total is the number of records matching the query, regardless of limit and offset. */
  total: number;
}

export interface ListTablesResp {
  tables: TableListItem[];
  total: number;
}

export interface Operation {
  actions: Action[];
  command: string;
}

export interface PreviewFieldShortcut {
  /** FieldUID is the UID of the field being edited or created. */
  fieldUID: string;
  /** Metadata is the unsaved metadata of the field, e.g. the options of the select fields. */
  metadata?: Record<string, any>;
  /** RecordUIDs are the records to preview, at most 3. */
  recordUIDs: string[];
  /** Shortcut is the unsaved shortcut config of the field. */
  shortcut: FieldShortcut;
  /** Type is the unsaved type of the field. */
  type:
    | "text"
    | "single_select"
    | "multi_select"
    | "datetime"
    | "number"
    | "checkbox";
}

export interface Profile {
  /** Color is the avatar color of the user. */
  color: string;
  createdAt: string;
  email: string;
  emailMd5: string;
  /** HasPassword reports whether the user has a password, the users created by third-party sign-in have none. */
  hasPassword: boolean;
  id: number;
  /** IsAdmin reports whether the user is a system admin. */
  isAdmin: boolean;
  userName: string;
}

export interface Project {
  createdAt: string;
  name: string;
  owner: UserBrief;
  /** Role is the permission of the signed-in user on the project. */
  role: "owner" | "manager" | "editor" | "viewer";
  uid: string;
  updatedAt: string;
}

export interface ProjectListItem {
  createdAt: string;
  name: string;
  owner: UserBrief;
  /** Role is the permission of the signed-in user on the project. */
  role: "owner" | "manager" | "editor" | "viewer";
  tableCount: number;
  uid: string;
  updatedAt: string;
}

export interface ProjectMember {
  role: "owner" | "manager" | "editor" | "viewer";
  user: UserBrief;
}

export interface QueryRecords {
  filter?: QueryRecordsFilter[];
  /** Group sorts the records by the field values before Order, so records in the same group are adjacent. */
  group?: QueryRecordsGroup[];
  /** Limit defaults to 20 when it is not positive. */
  limit?: number;
  offset?: number;
  order?: QueryRecordsSort[];
}

export interface QueryRecordsFilter {
  fieldUID: string;
  operation: "eq" | "neq" | "gt" | "lt" | "gte" | "lte" | "in" | "nin" | "like";
  /** Value is a JSON array (e.g. `["a","b"]`) for in / nin, and a single value for other operations. */
  value: string;
}

export interface QueryRecordsGroup {
  fieldUID: string;
}

export interface QueryRecordsSort {
  fieldUID: string;
  order?: "asc" | "desc";
}

export interface RunFieldShortcut {
  /** RecordUIDs are the records to generate if Scope is records. */
  recordUIDs?: string[];
  /** Scope is all the records, the records whose cell is empty, or the given records. */
  scope: "all" | "empty" | "records";
}

export interface RunFieldShortcutResp {
  /** Count is the number of the cells queued. */
  count: number;
}

export interface SLField {
  /** CreatedAt is the time the field was created. */
  createdAt: string;
  /** Label is the title of the field. */
  label: string;
  /** Metadata is the type-specific configuration, e.g. select options or the formula expression. */
  metadata: Record<string, any>;
  /** Position is the order of the field in the table, starting from 0. The first field is the primary field. */
  position: number;
  /** Shortcut generates the cell values from the other fields, it is absent if the values are edited by the users. */
  shortcut?: FieldShortcut;
  /** TableUID is the table of the field. */
  tableUID: string;
  /** Type is the type of the field. */
  type:
    | "text"
    | "single_select"
    | "multi_select"
    | "datetime"
    | "number"
    | "checkbox"
    | "formula";
  /** UID is the identifier of the field, which is also the key of its values in the record data. */
  uid: string;
  /** UpdatedAt is the time the field was last updated. */
  updatedAt: string;
}

export interface SLRecord {
  createdAt: string;
  /** Data is the cell values keyed by field UID. */
  data: Record<string, any>;
  tableUID: string;
  uid: string;
  updatedAt: string;
}

export interface SLTable {
  createdAt: string;
  name: string;
  projectUID: string;
  uid: string;
  updatedAt: string;
}

export interface SLView {
  /** Config is maintained by the frontend, e.g. filter, sort, group, hidden fields and field widths. */
  config: Record<string, any>;
  name: string;
  position: number;
  tableUID: string;
  type: "grid" | "kanban" | "gallery" | "form";
  uid: string;
}

export interface SaveFieldShortcut {
  /** Code defines `async function execute(params, context)`. */
  code: string;
  /** Credentials are the credentials the script can use when fetching. */
  credentials: SaveShortcutCredential[];
  /** Description tells the members what the shortcut does, at most 500 characters. */
  description: string;
  /** Domains are the hosts the script can fetch, including their subdomains. */
  domains: string[];
  /** Enabled reports whether the members can attach and execute the shortcut. */
  enabled: boolean;
  /** FormItems are the inputs configured in the field editor and passed to execute as the params. */
  formItems: ShortcutFormItem[];
  /** Name is shown in the field editor, at most 64 characters. */
  name: string;
  /** ResultType is the type of the fields the shortcut can be attached to. */
  resultType:
    | "text"
    | "single_select"
    | "multi_select"
    | "datetime"
    | "number"
    | "checkbox";
  /** TimeoutSeconds is the time limit of an execution between 1 and 300, 0 defaults to 30. */
  timeoutSeconds: number;
}

export interface SaveShortcutCredential {
  /** Key is the identifier the script passes to context.fetch to use the credential. */
  key: string;
  /** Name is the header or query parameter name, it is ignored by bearer. */
  name?: string;
  /** Type is how the credential is put into the request. */
  type: "bearer" | "header" | "query";
  /** Value replaces the saved value, empty keeps the saved one. */
  value?: string;
}

export interface SetAuthProviderPositions {
  ids: number[];
}

export interface ShortcutFormItem {
  /** Component is the control to render the item. */
  component: "field_select" | "input" | "textarea" | "select" | "prompt";
  /** Default is the initial value when configuring a new field. */
  default?: string;
  /** FieldTypes limits the fields of field_select, empty allows all the fields except formulas. */
  fieldTypes?: string[];
  /** Key is the key of the configured value in FieldShortcut.Inputs and of the parameter passed to the shortcut. */
  key: string;
  /** Label is the name of the item shown in the form. */
  label: string;
  /** Options are the choices of select. */
  options?: ShortcutFormOption[];
  /** Placeholder is the hint of the empty input. */
  placeholder?: string;
  /** Required reports whether the item must be filled in before saving or executing. */
  required?: boolean;
}

export interface ShortcutFormOption {
  /** Label is the text of the option shown in the form. */
  label: string;
  /** Value is the configured value of the option. */
  value: string;
}

export interface ShortcutJob {
  /** Error is the reason of the failure, or of the last attempt of a pending retry. */
  error?: string;
  /** FieldUID is the field of the cell. */
  fieldUID: string;
  /** RecordUID is the record of the cell. */
  recordUID: string;
  /** Status is done when the job is removed, which is only sent over WebSocket. */
  status: "pending" | "running" | "failed" | "done";
}

export interface ShortcutPreview {
  /** Error is the reason of the failure, empty if succeeded. */
  error?: string;
  /** RecordUID is the record previewed. */
  recordUID: string;
  /** Value is the cell value of the field, null if empty or failed. */
  value?: object;
}

export interface SignIn {
  email: string;
  password: string;
}

export interface SignUp {
  email: string;
  /** Password is limited to 64 characters since bcrypt only uses the first 72 bytes. */
  password: string;
  userName: string;
}

export interface SiteAuthProvider {
  icon: string;
  name: string;
  slug: string;
  type: "oauth2" | "oidc" | "saml" | "ldap";
}

export interface SiteInfo {
  /** AllowPasswordSignIn being false shows only the third-party sign-in on the sign-in page, admins can still use a password. */
  allowPasswordSignIn: boolean;
  allowSignUp: boolean;
  /** LoginNotice is the plain text shown above the sign-in form, empty if hidden. */
  loginNotice: string;
  passwordMinLength: number;
  /** Providers are the enabled and usable sign-in methods in the order of the admin console. */
  providers: SiteAuthProvider[];
  siteName: string;
}

export interface SystemSettings {
  /** AllowPasswordSignIn being false allows only the admins to sign in with email and password. */
  allowPasswordSignIn: boolean;
  /** AllowSignUp reports whether new users can sign up by themselves. */
  allowSignUp: boolean;
  /** ExternalURL is the address users visit (e.g. https://sayrud.example.com), the callback URLs of third-party sign-in are built on it, empty if not set. */
  externalURL: string;
  /** LoginNotice is the plain text shown above the sign-in form, empty if hidden. */
  loginNotice: string;
  /** PasswordMinLength applies to signing up, changing, creating and resetting passwords. */
  passwordMinLength: number;
  /** SessionTTLDays is the lifetime in days of the new sessions. */
  sessionTTLDays: number;
  /** SiteName is shown in the page title and the sign-in page. */
  siteName: string;
}

export interface TableListItem {
  count: number;
  createdAt: string;
  name: string;
  projectUID: string;
  uid: string;
  updatedAt: string;
}

export interface TableSnapshot {
  fields: SLField[];
  records: SLRecord[];
  rev: number;
  table: SLTable;
  views: SLView[];
}

export interface TestAISettingsResp {
  /** DurationMs is the time of the request in milliseconds. */
  durationMs: number;
  /** Reply is the content returned by the model, truncated to 500 characters. */
  reply: string;
}

export interface TestAuthProvider {
  /** BindPassword is the password of the LDAP service account. */
  bindPassword?: string;
  config: AuthProviderConfig;
  /** ID is the saved provider whose secrets are used if empty, 0 when creating. */
  id?: number;
  type: "oauth2" | "oidc" | "saml" | "ldap";
  /** Username is the LDAP user to search, optional. */
  username?: string;
}

export interface TestFieldShortcut {
  /** Params are passed to execute as is, keyed by the form item key. */
  params: Record<string, any>;
  /** Shortcut is the unsaved shortcut to run. */
  shortcut: SaveFieldShortcut;
  /** UID is the saved shortcut whose credential values are used if the values are not given. */
  uid?: string;
}

export interface TestFieldShortcutResp {
  /** CellValue is the value converted for a field of the result type, select fields are not converted as there are no options. */
  cellValue?: object;
  /** DurationMs is the time of the run in milliseconds. */
  durationMs: number;
  /** Error is the reason of the failure, empty if succeeded. */
  error?: string;
  /** Logs are the lines printed by console and context.log, with the credential values redacted. */
  logs: string[];
  /** Value is the value returned by execute, before converting to the cell value. */
  value?: object;
}

export interface TransferProjectOwner {
  userID: number;
}

export interface UpdateAISettings {
  /** APIKey replaces the saved one, empty keeps the saved one. */
  apiKey?: string;
  /** BaseURL is the API root including the version, e.g. https://api.openai.com/v1. */
  baseURL: string;
  /** ClearAPIKey removes the saved API key, it is ignored if APIKey is given. */
  clearAPIKey?: boolean;
  /** Enabled reports whether the global AI model is enabled. */
  enabled: boolean;
  /** Model is the name of the model to call, it is required if enabled. */
  model: string;
  /** TimeoutSeconds is the timeout of a completion request, between 1 and 120. */
  timeoutSeconds: number;
}

export interface UpdateAuthProvider {
  allowedEmailDomains: string[];
  allowedGroups: string[];
  autoCreateUser: boolean;
  /** BindPassword is the password of the LDAP service account, empty keeps the saved one when updating. */
  bindPassword?: string;
  /** ClientSecret is the client secret of OAuth 2.0 or OIDC, empty keeps the saved one when updating. */
  clientSecret?: string;
  config: AuthProviderConfig;
  enabled: boolean;
  icon: string;
  linkByEmail: boolean;
  name: string;
}

export interface UpdateField {
  label?: string;
  /** Metadata replaces the whole field configuration, it is required when the type changes. */
  metadata?: Record<string, any>;
  type?:
    | "text"
    | "single_select"
    | "multi_select"
    | "datetime"
    | "number"
    | "checkbox"
    | "formula";
}

export interface UpdateFieldPosition {
  /** Position is the zero-based index the field moves to, it is clamped into the valid range. */
  position: number;
}

export interface UpdatePassword {
  newPassword: string;
  oldPassword: string;
}

export interface UpdateProfile {
  userName: string;
}

export interface UpdateProject {
  name: string;
}

export interface UpdateProjectMember {
  role: "manager" | "editor" | "viewer";
}

export interface UpdateRecord {
  /** Data replaces all the cell values of the record, keyed by field UID. */
  data: Record<string, any>;
}

export interface UpdateSystemSettings {
  allowPasswordSignIn: boolean;
  allowSignUp: boolean;
  /** ExternalURL is the external URL of the site, empty if not set. */
  externalURL: string;
  /** LoginNotice is the plain text shown above the sign-in form, empty if hidden. */
  loginNotice: string;
  passwordMinLength: number;
  sessionTTLDays: number;
  siteName: string;
}

export interface UpdateTable {
  name: string;
}

export interface UpdateUserSettings {
  language?:
    | "en"
    | "zh-CN"
    | "zh-TW"
    | "ja"
    | "ko"
    | "es"
    | "pt-BR"
    | "fr"
    | "de"
    | "ru";
  theme?: "light" | "dark" | "system";
}

export interface UserBrief {
  color: string;
  email: string;
  emailMd5: string;
  id: number;
  userName: string;
}

export interface UserIdentity {
  createdAt: string;
  email: string;
  id: number;
  lastUsedAt: string;
  providerIcon: string;
  providerName: string;
  providerSlug: string;
  providerType: "oauth2" | "oidc" | "saml" | "ldap";
}

export interface UserSession {
  createdAt: string;
  /** Current reports whether it is the session of the current request. */
  current: boolean;
  expiresAt: string;
  id: number;
  ip: string;
  userAgent: string;
}

export interface UserSettings {
  /** Language is the language of the user interface. */
  language:
    | "en"
    | "zh-CN"
    | "zh-TW"
    | "ja"
    | "ko"
    | "es"
    | "pt-BR"
    | "fr"
    | "de"
    | "ru";
  /** Theme is the appearance of the user interface. */
  theme: "light" | "dark" | "system";
}

export interface ViewAttrs {
  config?: Record<string, any>;
  name?: string;
  type?: "grid" | "kanban" | "gallery" | "form";
}

export type GetAdminAiSettingsData = AdminAISettings;

export type UpdateAdminAiSettingsData = AdminAISettings;

export type TestAdminAiSettingsData = TestAISettingsResp;

export type ListAdminAuthProvidersData = ListAdminAuthProvidersResp;

export type CreateAdminAuthProviderData = AdminAuthProvider;

export type SetAdminAuthProviderPositionsData = any;

export type TestAdminAuthProviderData = any;

export type UpdateAdminAuthProviderData = AdminAuthProvider;

export type DeleteAdminAuthProviderData = any;

export type ListAdminFieldShortcutsData = AdminFieldShortcut[];

export type CreateAdminFieldShortcutData = AdminFieldShortcut;

export type TestAdminFieldShortcutData = TestFieldShortcutResp;

export type GetAdminFieldShortcutData = AdminFieldShortcut;

export type UpdateAdminFieldShortcutData = AdminFieldShortcut;

export type DeleteAdminFieldShortcutData = any;

export type GetAdminOverviewData = AdminOverview;

export type ListAdminProjectsData = ListAdminProjectsResp;

export type DeleteAdminProjectData = any;

export type TransferAdminProjectData = any;

export type GetSystemSettingsData = SystemSettings;

export type UpdateSystemSettingsData = SystemSettings;

export type ListAdminUsersData = ListAdminUsersResp;

export type CreateAdminUserData = AdminUser;

export type UpdateAdminUserData = any;

export type DeleteAdminUserData = any;

export type SetAdminUserAdminData = any;

export type ResetAdminUserPasswordData = any;

export type RevokeAdminUserSessionsData = any;

export type SetAdminUserStatusData = any;

export type DeleteAccountData = any;

export type ListIdentitiesData = UserIdentity[];

export type DeleteIdentityData = any;

export type LdapSignInData = Profile;

export type UpdatePasswordData = any;

export type GetProfileData = Profile;

export type UpdateProfileData = Profile;

export type ListSessionsData = UserSession[];

export type RevokeOtherSessionsData = any;

export type RevokeSessionData = any;

export type GetUserSettingsData = UserSettings;

export type UpdateUserSettingsData = UserSettings;

export type SignInData = Profile;

export type SignOutData = any;

export type SignUpData = Profile;

export type SsoMetadataData = string;

export type ListProjectsData = ListProjectsResp;

export type CreateProjectData = Project;

export type GetProjectData = Project;

export type UpdateProjectData = any;

export type DeleteProjectData = any;

export type AiAdviceData = AIAdviceResp;

export type AiApplyData = any;

export type ListFieldShortcutsData = FieldShortcutManifest[];

export type ListProjectMembersData = ProjectMember[];

export type AddProjectMemberData = ProjectMember;

export type LookupProjectMemberCandidateData = UserBrief;

export type UpdateProjectMemberData = any;

export type RemoveProjectMemberData = any;

export type TransferProjectOwnerData = any;

export type ListTablesData = ListTablesResp;

export type CreateTableData = SLTable;

export type ListFieldTypesData = Record<string, string>;

export type GetTableData = SLTable;

export type UpdateTableData = any;

export type DeleteTableData = any;

export type ListChangesetsData = ListChangesetsResp;

export type ListFieldsData = SLField[];

export type CreateFieldsData = SLField[];

export type UpdateFieldData = SLField;

export type DeleteFieldData = any;

export type UpdateFieldPositionData = any;

export type RunFieldShortcutData = RunFieldShortcutResp;

export type ListRecordsData = ListRecordsResp;

export type CreateRecordData = SLRecord;

export type BatchCreateRecordsData = SLRecord[];

export type FetchRecordsData = SLRecord[];

export type QueryRecordsData = ListRecordsResp;

export type GetRecordData = SLRecord;

export type UpdateRecordData = any;

export type DeleteRecordData = any;

export type ListShortcutJobsData = ShortcutJob[];

export type PreviewFieldShortcutData = ShortcutPreview[];

export type GetTableSnapshotData = TableSnapshot;

export type ListViewsData = SLView[];

export type GetSiteInfoData = SiteInfo;

import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse,
  HeadersDefaults,
  ResponseType,
} from "axios";
import axios from "axios";

export type QueryParamsType = Record<string | number, any>;

export interface FullRequestParams
  extends Omit<AxiosRequestConfig, "data" | "params" | "url" | "responseType"> {
  /** set parameter to `true` for call `securityWorker` for this request */
  secure?: boolean;
  /** request path */
  path: string;
  /** content type of request body */
  type?: ContentType;
  /** query params */
  query?: QueryParamsType;
  /** format of response (i.e. response.json() -> format: "json") */
  format?: ResponseType;
  /** request body */
  body?: unknown;
}

export type RequestParams = Omit<
  FullRequestParams,
  "body" | "method" | "query" | "path"
>;

export interface ApiConfig<SecurityDataType = unknown>
  extends Omit<AxiosRequestConfig, "data" | "cancelToken"> {
  securityWorker?: (
    securityData: SecurityDataType | null,
  ) => Promise<AxiosRequestConfig | void> | AxiosRequestConfig | void;
  secure?: boolean;
  format?: ResponseType;
}

export enum ContentType {
  Json = "application/json",
  JsonApi = "application/vnd.api+json",
  FormData = "multipart/form-data",
  UrlEncoded = "application/x-www-form-urlencoded",
  Text = "text/plain",
}

export class HttpClient<SecurityDataType = unknown> {
  public instance: AxiosInstance;
  private securityData: SecurityDataType | null = null;
  private securityWorker?: ApiConfig<SecurityDataType>["securityWorker"];
  private secure?: boolean;
  private format?: ResponseType;

  constructor({
    securityWorker,
    secure,
    format,
    ...axiosConfig
  }: ApiConfig<SecurityDataType> = {}) {
    this.instance = axios.create({
      ...axiosConfig,
      baseURL: axiosConfig.baseURL || "/_",
    });
    this.secure = secure;
    this.format = format;
    this.securityWorker = securityWorker;
  }

  public setSecurityData = (data: SecurityDataType | null) => {
    this.securityData = data;
  };

  protected mergeRequestParams(
    params1: AxiosRequestConfig,
    params2?: AxiosRequestConfig,
  ): AxiosRequestConfig {
    const method = params1.method || (params2 && params2.method);

    return {
      ...this.instance.defaults,
      ...params1,
      ...(params2 || {}),
      headers: {
        ...((method &&
          this.instance.defaults.headers[
            method.toLowerCase() as keyof HeadersDefaults
          ]) ||
          {}),
        ...(params1.headers || {}),
        ...((params2 && params2.headers) || {}),
      },
    };
  }

  protected stringifyFormItem(formItem: unknown) {
    if (typeof formItem === "object" && formItem !== null) {
      return JSON.stringify(formItem);
    } else {
      return `${formItem}`;
    }
  }

  protected createFormData(input: Record<string, unknown>): FormData {
    if (input instanceof FormData) {
      return input;
    }
    return Object.keys(input || {}).reduce((formData, key) => {
      const property = input[key];
      const propertyContent: any[] =
        property instanceof Array ? property : [property];

      for (const formItem of propertyContent) {
        const isFileType = formItem instanceof Blob || formItem instanceof File;
        formData.append(
          key,
          isFileType ? formItem : this.stringifyFormItem(formItem),
        );
      }

      return formData;
    }, new FormData());
  }

  public request = async <T = any, _E = any>({
    secure,
    path,
    type,
    query,
    format,
    body,
    ...params
  }: FullRequestParams): Promise<AxiosResponse<T>> => {
    const secureParams =
      ((typeof secure === "boolean" ? secure : this.secure) &&
        this.securityWorker &&
        (await this.securityWorker(this.securityData))) ||
      {};
    const requestParams = this.mergeRequestParams(params, secureParams);
    const responseFormat = format || this.format || undefined;

    if (
      type === ContentType.FormData &&
      body &&
      body !== null &&
      typeof body === "object"
    ) {
      body = this.createFormData(body as Record<string, unknown>);
    }

    if (
      type === ContentType.Text &&
      body &&
      body !== null &&
      typeof body !== "string"
    ) {
      body = JSON.stringify(body);
    }

    return this.instance.request({
      ...requestParams,
      headers: {
        ...(requestParams.headers || {}),
        ...(type ? { "Content-Type": type } : {}),
      },
      params: query,
      responseType: responseFormat,
      data: body,
      url: path,
    });
  };
}

/**
 * @title Sayrud API
 * @version 1.0
 * @baseUrl /_
 * @contact
 */
export class Api<
  SecurityDataType extends unknown,
> extends HttpClient<SecurityDataType> {
  admin = {
    /**
     * @description Requires the admin. The API key is not returned.
     *
     * @name GetAdminAiSettings
     * @summary Get the AI model settings
     * @request GET:/admin/ai
     */
    getAdminAiSettings: (params: RequestParams = {}) =>
      this.request<GetAdminAiSettingsData, string>({
        path: `/admin/ai`,
        method: "GET",
        format: "json",
        ...params,
      }),

    /**
     * @description Requires the admin. The API key is encrypted by auth.secret_key, empty keeps the saved one. It updates the global AI model configuration immediately.
     *
     * @name UpdateAdminAiSettings
     * @summary Update the AI model settings
     * @request PUT:/admin/ai
     */
    updateAdminAiSettings: (
      data: UpdateAISettings,
      params: RequestParams = {},
    ) =>
      this.request<UpdateAdminAiSettingsData, string>({
        path: `/admin/ai`,
        method: "PUT",
        body: data,
        type: ContentType.Json,
        format: "json",
        ...params,
      }),

    /**
     * @description Requires the admin. Send a short message to the unsaved model, the saved API key is used if it is not given.
     *
     * @name TestAdminAiSettings
     * @summary Test the AI model settings
     * @request POST:/admin/ai/test
     */
    testAdminAiSettings: (data: UpdateAISettings, params: RequestParams = {}) =>
      this.request<TestAdminAiSettingsData, string>({
        path: `/admin/ai/test`,
        method: "POST",
        body: data,
        type: ContentType.Json,
        format: "json",
        ...params,
      }),

    /**
     * @description Requires the admin. The secrets are not returned.
     *
     * @name ListAdminAuthProviders
     * @summary List the sign-in methods
     * @request GET:/admin/auth-providers
     */
    listAdminAuthProviders: (params: RequestParams = {}) =>
      this.request<ListAdminAuthProvidersData, string>({
        path: `/admin/auth-providers`,
        method: "GET",
        format: "json",
        ...params,
      }),

    /**
     * @description Requires the admin and auth.secret_key in the config file. The SAML service provider certificate is generated automatically.
     *
     * @name CreateAdminAuthProvider
     * @summary Create a sign-in method
     * @request POST:/admin/auth-providers
     */
    createAdminAuthProvider: (
      data: CreateAuthProvider,
      params: RequestParams = {},
    ) =>
      this.request<CreateAdminAuthProviderData, string>({
        path: `/admin/auth-providers`,
        method: "POST",
        body: data,
        type: ContentType.Json,
        format: "json",
        ...params,
      }),

    /**
     * @description Requires the admin. The sign-in page shows them in this order.
     *
     * @name SetAdminAuthProviderPositions
     * @summary Reorder the sign-in methods
     * @request PUT:/admin/auth-providers/positions
     */
    setAdminAuthProviderPositions: (
      data: SetAuthProviderPositions,
      params: RequestParams = {},
    ) =>
      this.request<SetAdminAuthProviderPositionsData, string>({
        path: `/admin/auth-providers/positions`,
        method: "PUT",
        body: data,
        type: ContentType.Json,
        ...params,
      }),

    /**
     * @description Requires the admin. OIDC fetches the discovery document, SAML loads the IdP metadata, LDAP binds the service account and optionally searches the user. OAuth 2.0 is not supported.
     *
     * @name TestAdminAuthProvider
     * @summary Test the connection of a sign-in method
     * @request POST:/admin/auth-providers/test
     */
    testAdminAuthProvider: (
      data: TestAuthProvider,
      params: RequestParams = {},
    ) =>
      this.request<TestAdminAuthProviderData, string>({
        path: `/admin/auth-providers/test`,
        method: "POST",
        body: data,
        type: ContentType.Json,
        ...params,
      }),

    /**
     * @description Requires the admin. The slug and the type can not be changed, the empty secrets keep the saved ones.
     *
     * @name UpdateAdminAuthProvider
     * @summary Update a sign-in method
     * @request PUT:/admin/auth-providers/{providerID}
     */
    updateAdminAuthProvider: (
      providerId: number,
      data: UpdateAuthProvider,
      params: RequestParams = {},
    ) =>
      this.request<UpdateAdminAuthProviderData, string>({
        path: `/admin/auth-providers/${providerId}`,
        method: "PUT",
        body: data,
        type: ContentType.Json,
        format: "json",
        ...params,
      }),

    /**
     * @description Requires the admin. The bound third-party accounts of the users are unbound.
     *
     * @name DeleteAdminAuthProvider
     * @summary Delete a sign-in method
     * @request DELETE:/admin/auth-providers/{providerID}
     */
    deleteAdminAuthProvider: (providerId: number, params: RequestParams = {}) =>
      this.request<DeleteAdminAuthProviderData, string>({
        path: `/admin/auth-providers/${providerId}`,
        method: "DELETE",
        ...params,
      }),

    /**
     * @description Requires the admin. The credential values are not returned.
     *
     * @name ListAdminFieldShortcuts
     * @summary List the custom field shortcuts
     * @request GET:/admin/field-shortcuts
     */
    listAdminFieldShortcuts: (params: RequestParams = {}) =>
      this.request<ListAdminFieldShortcutsData, string>({
        path: `/admin/field-shortcuts`,
        method: "GET",
        format: "json",
        ...params,
      }),

    /**
     * @description Requires the admin. The credential values are encrypted by auth.secret_key.
     *
     * @name CreateAdminFieldShortcut
     * @summary Create a custom field shortcut
     * @request POST:/admin/field-shortcuts
     */
    createAdminFieldShortcut: (
      data: SaveFieldShortcut,
      params: RequestParams = {},
    ) =>
      this.request<CreateAdminFieldShortcutData, string>({
        path: `/admin/field-shortcuts`,
        method: "POST",
        body: data,
        type: ContentType.Json,
        format: "json",
        ...params,
      }),

    /**
     * @description Requires the admin. Run the unsaved code with the parameters, and return the result and the logs.
     *
     * @name TestAdminFieldShortcut
     * @summary Test a custom field shortcut
     * @request POST:/admin/field-shortcuts/test
     */
    testAdminFieldShortcut: (
      data: TestFieldShortcut,
      params: RequestParams = {},
    ) =>
      this.request<TestAdminFieldShortcutData, string>({
        path: `/admin/field-shortcuts/test`,
        method: "POST",
        body: data,
        type: ContentType.Json,
        format: "json",
        ...params,
      }),

    /**
     * @description Requires the admin. The credential values are not returned.
     *
     * @name GetAdminFieldShortcut
     * @summary Get a custom field shortcut
     * @request GET:/admin/field-shortcuts/{shortcutUID}
     */
    getAdminFieldShortcut: (shortcutUid: string, params: RequestParams = {}) =>
      this.request<GetAdminFieldShortcutData, string>({
        path: `/admin/field-shortcuts/${shortcutUid}`,
        method: "GET",
        format: "json",
        ...params,
      }),

    /**
     * @description Requires the admin. The empty credential values keep the saved ones.
     *
     * @name UpdateAdminFieldShortcut
     * @summary Update a custom field shortcut
     * @request PUT:/admin/field-shortcuts/{shortcutUID}
     */
    updateAdminFieldShortcut: (
      shortcutUid: string,
      data: SaveFieldShortcut,
      params: RequestParams = {},
    ) =>
      this.request<UpdateAdminFieldShortcutData, string>({
        path: `/admin/field-shortcuts/${shortcutUid}`,
        method: "PUT",
        body: data,
        type: ContentType.Json,
        format: "json",
        ...params,
      }),

    /**
     * @description Requires the admin. The fields using it keep their values, and fail to generate new ones.
     *
     * @name DeleteAdminFieldShortcut
     * @summary Delete a custom field shortcut
     * @request DELETE:/admin/field-shortcuts/{shortcutUID}
     */
    deleteAdminFieldShortcut: (
      shortcutUid: string,
      params: RequestParams = {},
    ) =>
      this.request<DeleteAdminFieldShortcutData, string>({
        path: `/admin/field-shortcuts/${shortcutUid}`,
        method: "DELETE",
        ...params,
      }),

    /**
     * @description Requires the admin.
     *
     * @name GetAdminOverview
     * @summary Get the overview of the system
     * @request GET:/admin/overview
     */
    getAdminOverview: (params: RequestParams = {}) =>
      this.request<GetAdminOverviewData, string>({
        path: `/admin/overview`,
        method: "GET",
        format: "json",
        ...params,
      }),

    /**
     * @description Requires the admin. The newest projects come first.
     *
     * @name ListAdminProjects
     * @summary List all the projects
     * @request GET:/admin/projects
     */
    listAdminProjects: (
      query?: {
        /** Page number, starting from 1 */
        page?: number;
        /** Page size, defaults to 20 */
        pageSize?: number;
        /** Matches the project name */
        keyword?: string;
      },
      params: RequestParams = {},
    ) =>
      this.request<ListAdminProjectsData, string>({
        path: `/admin/projects`,
        method: "GET",
        query: query,
        format: "json",
        ...params,
      }),

    /**
     * @description Requires the admin.
     *
     * @name DeleteAdminProject
     * @summary Delete a project
     * @request DELETE:/admin/projects/{projectUID}
     */
    deleteAdminProject: (projectUid: string, params: RequestParams = {}) =>
      this.request<DeleteAdminProjectData, string>({
        path: `/admin/projects/${projectUid}`,
        method: "DELETE",
        ...params,
      }),

    /**
     * @description Requires the admin. The new owner can be any enabled user, the previous owner becomes a manager.
     *
     * @name TransferAdminProject
     * @summary Transfer the ownership of a project
     * @request PUT:/admin/projects/{projectUID}/owner
     */
    transferAdminProject: (
      projectUid: string,
      data: AdminTransferProject,
      params: RequestParams = {},
    ) =>
      this.request<TransferAdminProjectData, string>({
        path: `/admin/projects/${projectUid}/owner`,
        method: "PUT",
        body: data,
        type: ContentType.Json,
        ...params,
      }),

    /**
     * @description Requires the admin.
     *
     * @name GetSystemSettings
     * @summary Get the system settings
     * @request GET:/admin/settings
     */
    getSystemSettings: (params: RequestParams = {}) =>
      this.request<GetSystemSettingsData, string>({
        path: `/admin/settings`,
        method: "GET",
        format: "json",
        ...params,
      }),

    /**
     * @description Requires the admin. The password and session settings apply to the later sign-ups and sign-ins.
     *
     * @name UpdateSystemSettings
     * @summary Update the system settings
     * @request PUT:/admin/settings
     */
    updateSystemSettings: (
      data: UpdateSystemSettings,
      params: RequestParams = {},
    ) =>
      this.request<UpdateSystemSettingsData, string>({
        path: `/admin/settings`,
        method: "PUT",
        body: data,
        type: ContentType.Json,
        format: "json",
        ...params,
      }),

    /**
     * @description Requires the admin. The newest users come first.
     *
     * @name ListAdminUsers
     * @summary List the users
     * @request GET:/admin/users
     */
    listAdminUsers: (
      query?: {
        /** Page number, starting from 1 */
        page?: number;
        /** Page size, defaults to 20 */
        pageSize?: number;
        /** Matches the user name or email */
        keyword?: string;
        /** Filter by status, all if empty */
        status?: "active" | "disabled" | "admin";
      },
      params: RequestParams = {},
    ) =>
      this.request<ListAdminUsersData, string>({
        path: `/admin/users`,
        method: "GET",
        query: query,
        format: "json",
        ...params,
      }),

    /**
     * @description Requires the admin. It works even if signing up is disabled.
     *
     * @name CreateAdminUser
     * @summary Create a user
     * @request POST:/admin/users
     */
    createAdminUser: (data: AdminCreateUser, params: RequestParams = {}) =>
      this.request<CreateAdminUserData, string>({
        path: `/admin/users`,
        method: "POST",
        body: data,
        type: ContentType.Json,
        format: "json",
        ...params,
      }),

    /**
     * @description Requires the admin.
     *
     * @name UpdateAdminUser
     * @summary Update the user name of a user
     * @request PUT:/admin/users/{userID}
     */
    updateAdminUser: (
      userId: number,
      data: AdminUpdateUser,
      params: RequestParams = {},
    ) =>
      this.request<UpdateAdminUserData, string>({
        path: `/admin/users/${userId}`,
        method: "PUT",
        body: data,
        type: ContentType.Json,
        ...params,
      }),

    /**
     * @description Requires the admin. The projects owned by the user are transferred to transferTo, which is required if there are any.
     *
     * @name DeleteAdminUser
     * @summary Delete a user
     * @request DELETE:/admin/users/{userID}
     */
    deleteAdminUser: (
      userId: number,
      query?: {
        /** User ID to receive the owned projects */
        transferTo?: number;
      },
      params: RequestParams = {},
    ) =>
      this.request<DeleteAdminUserData, string>({
        path: `/admin/users/${userId}`,
        method: "DELETE",
        query: query,
        ...params,
      }),

    /**
     * @description Requires the admin. The admin can not revoke itself, and at least one enabled admin is kept.
     *
     * @name SetAdminUserAdmin
     * @summary Grant or revoke the admin
     * @request PUT:/admin/users/{userID}/admin
     */
    setAdminUserAdmin: (
      userId: number,
      data: AdminSetUserAdmin,
      params: RequestParams = {},
    ) =>
      this.request<SetAdminUserAdminData, string>({
        path: `/admin/users/${userId}/admin`,
        method: "PUT",
        body: data,
        type: ContentType.Json,
        ...params,
      }),

    /**
     * @description Requires the admin. The user is signed out everywhere.
     *
     * @name ResetAdminUserPassword
     * @summary Reset the password of a user
     * @request PUT:/admin/users/{userID}/password
     */
    resetAdminUserPassword: (
      userId: number,
      data: AdminResetPassword,
      params: RequestParams = {},
    ) =>
      this.request<ResetAdminUserPasswordData, string>({
        path: `/admin/users/${userId}/password`,
        method: "PUT",
        body: data,
        type: ContentType.Json,
        ...params,
      }),

    /**
     * @description Requires the admin. Use the account settings for the admin itself.
     *
     * @name RevokeAdminUserSessions
     * @summary Sign out a user everywhere
     * @request DELETE:/admin/users/{userID}/sessions
     */
    revokeAdminUserSessions: (userId: number, params: RequestParams = {}) =>
      this.request<RevokeAdminUserSessionsData, string>({
        path: `/admin/users/${userId}/sessions`,
        method: "DELETE",
        ...params,
      }),

    /**
     * @description Requires the admin. Disabling signs the user out everywhere. The admin can not disable itself, and at least one enabled admin is kept.
     *
     * @name SetAdminUserStatus
     * @summary Disable or enable a user
     * @request PUT:/admin/users/{userID}/status
     */
    setAdminUserStatus: (
      userId: number,
      data: AdminSetUserStatus,
      params: RequestParams = {},
    ) =>
      this.request<SetAdminUserStatusData, string>({
        path: `/admin/users/${userId}/status`,
        method: "PUT",
        body: data,
        type: ContentType.Json,
        ...params,
      }),
  };
  auth = {
    /**
     * @description The projects owned by the user must be deleted or transferred first, and the last admin can not be deleted. Users without a password confirm with their email instead.
     *
     * @name DeleteAccount
     * @summary Delete the account of the signed-in user
     * @request DELETE:/auth/account
     */
    deleteAccount: (data: DeleteAccount, params: RequestParams = {}) =>
      this.request<DeleteAccountData, string>({
        path: `/auth/account`,
        method: "DELETE",
        body: data,
        type: ContentType.Json,
        ...params,
      }),

    /**
     * No description
     *
     * @name ListIdentities
     * @summary List the third-party accounts bound to the signed-in user
     * @request GET:/auth/identities
     */
    listIdentities: (params: RequestParams = {}) =>
      this.request<ListIdentitiesData, string>({
        path: `/auth/identities`,
        method: "GET",
        format: "json",
        ...params,
      }),

    /**
     * @description The last way to sign in can not be unbound if the user has no password.
     *
     * @name DeleteIdentity
     * @summary Unbind a third-party account of the signed-in user
     * @request DELETE:/auth/identities/{identityID}
     */
    deleteIdentity: (identityId: number, params: RequestParams = {}) =>
      this.request<DeleteIdentityData, string>({
        path: `/auth/identities/${identityId}`,
        method: "DELETE",
        ...params,
      }),

    /**
     * No description
     *
     * @name LdapSignIn
     * @summary Sign in with LDAP
     * @request POST:/auth/ldap/{slug}/sign-in
     */
    ldapSignIn: (slug: string, data: LDAPSignIn, params: RequestParams = {}) =>
      this.request<LdapSignInData, string>({
        path: `/auth/ldap/${slug}/sign-in`,
        method: "POST",
        body: data,
        type: ContentType.Json,
        format: "json",
        ...params,
      }),

    /**
     * @description The other sessions of the user are signed out.
     *
     * @name UpdatePassword
     * @summary Change the password of the signed-in user
     * @request PUT:/auth/password
     */
    updatePassword: (data: UpdatePassword, params: RequestParams = {}) =>
      this.request<UpdatePasswordData, string>({
        path: `/auth/password`,
        method: "PUT",
        body: data,
        type: ContentType.Json,
        ...params,
      }),

    /**
     * No description
     *
     * @name GetProfile
     * @summary Get the profile of the signed-in user
     * @request GET:/auth/profile
     */
    getProfile: (params: RequestParams = {}) =>
      this.request<GetProfileData, string>({
        path: `/auth/profile`,
        method: "GET",
        format: "json",
        ...params,
      }),

    /**
     * No description
     *
     * @name UpdateProfile
     * @summary Update the profile of the signed-in user
     * @request PUT:/auth/profile
     */
    updateProfile: (data: UpdateProfile, params: RequestParams = {}) =>
      this.request<UpdateProfileData, string>({
        path: `/auth/profile`,
        method: "PUT",
        body: data,
        type: ContentType.Json,
        format: "json",
        ...params,
      }),

    /**
     * @description The unexpired sessions, the newest first.
     *
     * @name ListSessions
     * @summary List the sign-in sessions of the signed-in user
     * @request GET:/auth/sessions
     */
    listSessions: (params: RequestParams = {}) =>
      this.request<ListSessionsData, string>({
        path: `/auth/sessions`,
        method: "GET",
        format: "json",
        ...params,
      }),

    /**
     * No description
     *
     * @name RevokeOtherSessions
     * @summary Sign out all the other sessions of the signed-in user
     * @request DELETE:/auth/sessions
     */
    revokeOtherSessions: (params: RequestParams = {}) =>
      this.request<RevokeOtherSessionsData, string>({
        path: `/auth/sessions`,
        method: "DELETE",
        ...params,
      }),

    /**
     * @description The current session can not be revoked here, sign out instead.
     *
     * @name RevokeSession
     * @summary Sign out a session of the signed-in user
     * @request DELETE:/auth/sessions/{sessionID}
     */
    revokeSession: (sessionId: number, params: RequestParams = {}) =>
      this.request<RevokeSessionData, string>({
        path: `/auth/sessions/${sessionId}`,
        method: "DELETE",
        ...params,
      }),

    /**
     * @description The personal settings synced across the devices, the unsaved ones take the defaults.
     *
     * @name GetUserSettings
     * @summary Get the settings of the signed-in user
     * @request GET:/auth/settings
     */
    getUserSettings: (params: RequestParams = {}) =>
      this.request<GetUserSettingsData, string>({
        path: `/auth/settings`,
        method: "GET",
        format: "json",
        ...params,
      }),

    /**
     * No description
     *
     * @name UpdateUserSettings
     * @summary Update the settings of the signed-in user
     * @request PUT:/auth/settings
     */
    updateUserSettings: (
      data: UpdateUserSettings,
      params: RequestParams = {},
    ) =>
      this.request<UpdateUserSettingsData, string>({
        path: `/auth/settings`,
        method: "PUT",
        body: data,
        type: ContentType.Json,
        format: "json",
        ...params,
      }),

    /**
     * No description
     *
     * @name SignIn
     * @summary Sign in with email and password
     * @request POST:/auth/sign-in
     */
    signIn: (data: SignIn, params: RequestParams = {}) =>
      this.request<SignInData, string>({
        path: `/auth/sign-in`,
        method: "POST",
        body: data,
        type: ContentType.Json,
        format: "json",
        ...params,
      }),

    /**
     * @description Revoke the current session and clear the session cookie.
     *
     * @name SignOut
     * @summary Sign out
     * @request POST:/auth/sign-out
     */
    signOut: (params: RequestParams = {}) =>
      this.request<SignOutData, string>({
        path: `/auth/sign-out`,
        method: "POST",
        ...params,
      }),

    /**
     * @description Create an account and sign in. The first user takes over the projects created before accounts were introduced.
     *
     * @name SignUp
     * @summary Sign up with email and password
     * @request POST:/auth/sign-up
     */
    signUp: (data: SignUp, params: RequestParams = {}) =>
      this.request<SignUpData, string>({
        path: `/auth/sign-up`,
        method: "POST",
        body: data,
        type: ContentType.Json,
        format: "json",
        ...params,
      }),

    /**
     * @description Receives the SAML response posted by the identity provider, signs in and redirects. Failures redirect with the sso_error query.
     *
     * @name SsoAcs
     * @summary SAML Assertion Consumer Service
     * @request POST:/auth/sso/{slug}/acs
     */
    ssoAcs: (slug: string, params: RequestParams = {}) =>
      this.request<any, void>({
        path: `/auth/sso/${slug}/acs`,
        method: "POST",
        type: ContentType.UrlEncoded,
        ...params,
      }),

    /**
     * @description Signs in (or binds the account in the link mode) and redirects to the saved path. Failures redirect with the sso_error query.
     *
     * @name SsoCallback
     * @summary OAuth 2.0 / OIDC callback
     * @request GET:/auth/sso/{slug}/callback
     */
    ssoCallback: (
      slug: string,
      query: {
        /** State */
        state: string;
        /** Authorization code */
        code?: string;
      },
      params: RequestParams = {},
    ) =>
      this.request<any, void>({
        path: `/auth/sso/${slug}/callback`,
        method: "GET",
        query: query,
        ...params,
      }),

    /**
     * @description The entity ID of the service provider is the URL of this metadata. Available before the provider is enabled.
     *
     * @name SsoMetadata
     * @summary SAML service provider metadata
     * @request GET:/auth/sso/{slug}/metadata
     */
    ssoMetadata: (slug: string, params: RequestParams = {}) =>
      this.request<SsoMetadataData, string>({
        path: `/auth/sso/${slug}/metadata`,
        method: "GET",
        ...params,
      }),

    /**
     * @description Redirects the browser to the identity provider. In the link mode the signed-in user binds the third-party account. Failures redirect to the sign-in page (or the security settings in the link mode) with the sso_error query.
     *
     * @name StartSso
     * @summary Start a third-party sign-in
     * @request GET:/auth/sso/{slug}/start
     */
    startSso: (
      slug: string,
      query?: {
        /** login or link, defaults to login */
        mode?: "login" | "link";
        /** Path to go after signing in */
        redirect?: string;
      },
      params: RequestParams = {},
    ) =>
      this.request<any, void>({
        path: `/auth/sso/${slug}/start`,
        method: "GET",
        query: query,
        ...params,
      }),
  };
  projects = {
    /**
     * @description List the projects owned by or shared with the signed-in user, with the number of tables in each project.
     *
     * @name ListProjects
     * @summary List projects
     * @request GET:/projects
     */
    listProjects: (
      query?: {
        /** Page number, starting from 1 */
        page?: number;
        /** Page size, defaults to 20 */
        pageSize?: number;
        /** owned: created by the user, shared: shared with the user, both if empty */
        scope?: "owned" | "shared";
      },
      params: RequestParams = {},
    ) =>
      this.request<ListProjectsData, string>({
        path: `/projects`,
        method: "GET",
        query: query,
        format: "json",
        ...params,
      }),

    /**
     * @description Create a project owned by the signed-in user.
     *
     * @name CreateProject
     * @summary Create a project
     * @request POST:/projects
     */
    createProject: (data: CreateProject, params: RequestParams = {}) =>
      this.request<CreateProjectData, string>({
        path: `/projects`,
        method: "POST",
        body: data,
        type: ContentType.Json,
        format: "json",
        ...params,
      }),

    /**
     * No description
     *
     * @name GetProject
     * @summary Get a project
     * @request GET:/projects/{projectUID}
     */
    getProject: (projectUid: string, params: RequestParams = {}) =>
      this.request<GetProjectData, string>({
        path: `/projects/${projectUid}`,
        method: "GET",
        format: "json",
        ...params,
      }),

    /**
     * @description Requires the editor role.
     *
     * @name UpdateProject
     * @summary Update a project
     * @request PUT:/projects/{projectUID}
     */
    updateProject: (
      projectUid: string,
      data: UpdateProject,
      params: RequestParams = {},
    ) =>
      this.request<UpdateProjectData, string>({
        path: `/projects/${projectUid}`,
        method: "PUT",
        body: data,
        type: ContentType.Json,
        ...params,
      }),

    /**
     * @description Delete the project along with its collaborators, only the owner can delete it.
     *
     * @name DeleteProject
     * @summary Delete a project
     * @request DELETE:/projects/{projectUID}
     */
    deleteProject: (projectUid: string, params: RequestParams = {}) =>
      this.request<DeleteProjectData, string>({
        path: `/projects/${projectUid}`,
        method: "DELETE",
        ...params,
      }),

    /**
     * @description Generate the advice of the action by AI from the conversation messages.
     *
     * @name AiAdvice
     * @summary Get table design advice from AI
     * @request POST:/projects/{projectUID}/ai/advice
     */
    aiAdvice: (
      projectUid: string,
      data: AIAdvice,
      params: RequestParams = {},
    ) =>
      this.request<AiAdviceData, string>({
        path: `/projects/${projectUid}/ai/advice`,
        method: "POST",
        body: data,
        type: ContentType.Json,
        format: "json",
        ...params,
      }),

    /**
     * @description Apply the actionJson returned by the advice API, e.g. create the advised tables.
     *
     * @name AiApply
     * @summary Apply the AI advice
     * @request POST:/projects/{projectUID}/ai/apply
     */
    aiApply: (projectUid: string, data: AIApply, params: RequestParams = {}) =>
      this.request<AiApplyData, string>({
        path: `/projects/${projectUid}/ai/apply`,
        method: "POST",
        body: data,
        type: ContentType.Json,
        ...params,
      }),

    /**
     * @description List the enabled custom shortcuts, with the forms to configure them.
     *
     * @name ListFieldShortcuts
     * @summary List field shortcuts
     * @request GET:/projects/{projectUID}/field-shortcuts
     */
    listFieldShortcuts: (projectUid: string, params: RequestParams = {}) =>
      this.request<ListFieldShortcutsData, string>({
        path: `/projects/${projectUid}/field-shortcuts`,
        method: "GET",
        format: "json",
        ...params,
      }),

    /**
     * @description List the owner and the collaborators of the project, the owner comes first.
     *
     * @name ListProjectMembers
     * @summary List the collaborators
     * @request GET:/projects/{projectUID}/members
     */
    listProjectMembers: (projectUid: string, params: RequestParams = {}) =>
      this.request<ListProjectMembersData, string>({
        path: `/projects/${projectUid}/members`,
        method: "GET",
        format: "json",
        ...params,
      }),

    /**
     * @description Add the registered user as a collaborator, or change the role if it has been one. Requires the manager role.
     *
     * @name AddProjectMember
     * @summary Add a collaborator
     * @request POST:/projects/{projectUID}/members
     */
    addProjectMember: (
      projectUid: string,
      data: AddProjectMember,
      params: RequestParams = {},
    ) =>
      this.request<AddProjectMemberData, string>({
        path: `/projects/${projectUid}/members`,
        method: "POST",
        body: data,
        type: ContentType.Json,
        format: "json",
        ...params,
      }),

    /**
     * @description Find the registered user by the exact email, requires the manager role.
     *
     * @name LookupProjectMemberCandidate
     * @summary Find a user to invite
     * @request GET:/projects/{projectUID}/members/lookup
     */
    lookupProjectMemberCandidate: (
      projectUid: string,
      query: {
        /** Email of the user */
        email: string;
      },
      params: RequestParams = {},
    ) =>
      this.request<LookupProjectMemberCandidateData, string>({
        path: `/projects/${projectUid}/members/lookup`,
        method: "GET",
        query: query,
        format: "json",
        ...params,
      }),

    /**
     * @description Requires the manager role, the owner and the signed-in user itself can not be changed.
     *
     * @name UpdateProjectMember
     * @summary Change the role of a collaborator
     * @request PUT:/projects/{projectUID}/members/{userID}
     */
    updateProjectMember: (
      projectUid: string,
      userId: number,
      data: UpdateProjectMember,
      params: RequestParams = {},
    ) =>
      this.request<UpdateProjectMemberData, string>({
        path: `/projects/${projectUid}/members/${userId}`,
        method: "PUT",
        body: data,
        type: ContentType.Json,
        ...params,
      }),

    /**
     * @description Requires the manager role, except that a collaborator can remove itself to leave the project. The owner can not be removed.
     *
     * @name RemoveProjectMember
     * @summary Remove a collaborator
     * @request DELETE:/projects/{projectUID}/members/{userID}
     */
    removeProjectMember: (
      projectUid: string,
      userId: number,
      params: RequestParams = {},
    ) =>
      this.request<RemoveProjectMemberData, string>({
        path: `/projects/${projectUid}/members/${userId}`,
        method: "DELETE",
        ...params,
      }),

    /**
     * @description Only the owner can transfer it to an existing collaborator, the previous owner becomes a manager.
     *
     * @name TransferProjectOwner
     * @summary Transfer the ownership of a project
     * @request PUT:/projects/{projectUID}/owner
     */
    transferProjectOwner: (
      projectUid: string,
      data: TransferProjectOwner,
      params: RequestParams = {},
    ) =>
      this.request<TransferProjectOwnerData, string>({
        path: `/projects/${projectUid}/owner`,
        method: "PUT",
        body: data,
        type: ContentType.Json,
        ...params,
      }),

    /**
     * @description List the tables of the project, with the number of records in each table.
     *
     * @name ListTables
     * @summary List tables
     * @request GET:/projects/{projectUID}/tables
     */
    listTables: (
      projectUid: string,
      query?: {
        /** Page number, starting from 1 */
        page?: number;
        /** Page size, defaults to 20 */
        pageSize?: number;
      },
      params: RequestParams = {},
    ) =>
      this.request<ListTablesData, string>({
        path: `/projects/${projectUid}/tables`,
        method: "GET",
        query: query,
        format: "json",
        ...params,
      }),

    /**
     * No description
     *
     * @name CreateTable
     * @summary Create a table
     * @request POST:/projects/{projectUID}/tables
     */
    createTable: (
      projectUid: string,
      data: CreateTable,
      params: RequestParams = {},
    ) =>
      this.request<CreateTableData, string>({
        path: `/projects/${projectUid}/tables`,
        method: "POST",
        body: data,
        type: ContentType.Json,
        format: "json",
        ...params,
      }),

    /**
     * @description Return the labels of all the field types, keyed by field type.
     *
     * @name ListFieldTypes
     * @summary List field types
     * @request GET:/projects/{projectUID}/tables/types
     */
    listFieldTypes: (projectUid: string, params: RequestParams = {}) =>
      this.request<ListFieldTypesData, string>({
        path: `/projects/${projectUid}/tables/types`,
        method: "GET",
        format: "json",
        ...params,
      }),

    /**
     * No description
     *
     * @name GetTable
     * @summary Get a table
     * @request GET:/projects/{projectUID}/tables/{tableUID}
     */
    getTable: (
      projectUid: string,
      tableUid: string,
      params: RequestParams = {},
    ) =>
      this.request<GetTableData, string>({
        path: `/projects/${projectUid}/tables/${tableUid}`,
        method: "GET",
        format: "json",
        ...params,
      }),

    /**
     * No description
     *
     * @name UpdateTable
     * @summary Update a table
     * @request PUT:/projects/{projectUID}/tables/{tableUID}
     */
    updateTable: (
      projectUid: string,
      tableUid: string,
      data: UpdateTable,
      params: RequestParams = {},
    ) =>
      this.request<UpdateTableData, string>({
        path: `/projects/${projectUid}/tables/${tableUid}`,
        method: "PUT",
        body: data,
        type: ContentType.Json,
        ...params,
      }),

    /**
     * No description
     *
     * @name DeleteTable
     * @summary Delete a table
     * @request DELETE:/projects/{projectUID}/tables/{tableUID}
     */
    deleteTable: (
      projectUid: string,
      tableUid: string,
      params: RequestParams = {},
    ) =>
      this.request<DeleteTableData, string>({
        path: `/projects/${projectUid}/tables/${tableUid}`,
        method: "DELETE",
        ...params,
      }),

    /**
     * @description Return the changesets whose revision is greater than since in revision order, for the client to catch up after missing broadcasts.
     *
     * @name ListChangesets
     * @summary List the missing changesets
     * @request GET:/projects/{projectUID}/tables/{tableUID}/changesets
     */
    listChangesets: (
      projectUid: string,
      tableUid: string,
      query: {
        /** The latest revision the client has applied */
        since: number;
      },
      params: RequestParams = {},
    ) =>
      this.request<ListChangesetsData, string>({
        path: `/projects/${projectUid}/tables/${tableUid}/changesets`,
        method: "GET",
        query: query,
        format: "json",
        ...params,
      }),

    /**
     * @description List all the fields of the table, ordered by position.
     *
     * @name ListFields
     * @summary List fields
     * @request GET:/projects/{projectUID}/tables/{tableUID}/fields
     */
    listFields: (
      projectUid: string,
      tableUid: string,
      params: RequestParams = {},
    ) =>
      this.request<ListFieldsData, string>({
        path: `/projects/${projectUid}/tables/${tableUid}/fields`,
        method: "GET",
        format: "json",
        ...params,
      }),

    /**
     * @description Create fields in batch, which are appended to the end of the table.
     *
     * @name CreateFields
     * @summary Create fields
     * @request POST:/projects/{projectUID}/tables/{tableUID}/fields
     */
    createFields: (
      projectUid: string,
      tableUid: string,
      data: CreateFields,
      params: RequestParams = {},
    ) =>
      this.request<CreateFieldsData, string>({
        path: `/projects/${projectUid}/tables/${tableUid}/fields`,
        method: "POST",
        body: data,
        type: ContentType.Json,
        format: "json",
        ...params,
      }),

    /**
     * @description Update the label, type or metadata of the field. Existing record values are kept as is when the type changes.
     *
     * @name UpdateField
     * @summary Update a field
     * @request PUT:/projects/{projectUID}/tables/{tableUID}/fields/{fieldUID}
     */
    updateField: (
      projectUid: string,
      tableUid: string,
      fieldUid: string,
      data: UpdateField,
      params: RequestParams = {},
    ) =>
      this.request<UpdateFieldData, string>({
        path: `/projects/${projectUid}/tables/${tableUid}/fields/${fieldUid}`,
        method: "PUT",
        body: data,
        type: ContentType.Json,
        format: "json",
        ...params,
      }),

    /**
     * No description
     *
     * @name DeleteField
     * @summary Delete a field
     * @request DELETE:/projects/{projectUID}/tables/{tableUID}/fields/{fieldUID}
     */
    deleteField: (
      projectUid: string,
      tableUid: string,
      fieldUid: string,
      params: RequestParams = {},
    ) =>
      this.request<DeleteFieldData, string>({
        path: `/projects/${projectUid}/tables/${tableUid}/fields/${fieldUid}`,
        method: "DELETE",
        ...params,
      }),

    /**
     * @description Move the field to the zero-based index among the table fields.
     *
     * @name UpdateFieldPosition
     * @summary Move a field
     * @request PUT:/projects/{projectUID}/tables/{tableUID}/fields/{fieldUID}/position
     */
    updateFieldPosition: (
      projectUid: string,
      tableUid: string,
      fieldUid: string,
      data: UpdateFieldPosition,
      params: RequestParams = {},
    ) =>
      this.request<UpdateFieldPositionData, string>({
        path: `/projects/${projectUid}/tables/${tableUid}/fields/${fieldUid}/position`,
        method: "PUT",
        body: data,
        type: ContentType.Json,
        ...params,
      }),

    /**
     * @description Queue the cells of the field to generate by its shortcut in the background, the progress is sent by the SHORTCUT_JOBS WebSocket messages.
     *
     * @name RunFieldShortcut
     * @summary Generate the cells of a field shortcut
     * @request POST:/projects/{projectUID}/tables/{tableUID}/fields/{fieldUID}/shortcut/run
     */
    runFieldShortcut: (
      projectUid: string,
      tableUid: string,
      fieldUid: string,
      data: RunFieldShortcut,
      params: RequestParams = {},
    ) =>
      this.request<RunFieldShortcutData, string>({
        path: `/projects/${projectUid}/tables/${tableUid}/fields/${fieldUid}/shortcut/run`,
        method: "POST",
        body: data,
        type: ContentType.Json,
        format: "json",
        ...params,
      }),

    /**
     * @description List the records of the table, the newest first.
     *
     * @name ListRecords
     * @summary List records
     * @request GET:/projects/{projectUID}/tables/{tableUID}/records
     */
    listRecords: (
      projectUid: string,
      tableUid: string,
      query?: {
        /** Maximum number of records, defaults to 20 */
        limit?: number;
        /** Number of records to skip */
        offset?: number;
      },
      params: RequestParams = {},
    ) =>
      this.request<ListRecordsData, string>({
        path: `/projects/${projectUid}/tables/${tableUid}/records`,
        method: "GET",
        query: query,
        format: "json",
        ...params,
      }),

    /**
     * No description
     *
     * @name CreateRecord
     * @summary Create a record
     * @request POST:/projects/{projectUID}/tables/{tableUID}/records
     */
    createRecord: (
      projectUid: string,
      tableUid: string,
      data: CreateRecord,
      params: RequestParams = {},
    ) =>
      this.request<CreateRecordData, string>({
        path: `/projects/${projectUid}/tables/${tableUid}/records`,
        method: "POST",
        body: data,
        type: ContentType.Json,
        format: "json",
        ...params,
      }),

    /**
     * @description Create multiple records atomically, none is created if any data is invalid.
     *
     * @name BatchCreateRecords
     * @summary Create records in batch
     * @request POST:/projects/{projectUID}/tables/{tableUID}/records/batch
     */
    batchCreateRecords: (
      projectUid: string,
      tableUid: string,
      data: BatchCreateRecords,
      params: RequestParams = {},
    ) =>
      this.request<BatchCreateRecordsData, string>({
        path: `/projects/${projectUid}/tables/${tableUid}/records/batch`,
        method: "POST",
        body: data,
        type: ContentType.Json,
        format: "json",
        ...params,
      }),

    /**
     * @description Return the records with the given UIDs in creation order, the deleted ones are omitted. It is used to reload the dirty records.
     *
     * @name FetchRecords
     * @summary Fetch records by UID
     * @request POST:/projects/{projectUID}/tables/{tableUID}/records/fetch
     */
    fetchRecords: (
      projectUid: string,
      tableUid: string,
      data: FetchRecords,
      params: RequestParams = {},
    ) =>
      this.request<FetchRecordsData, string>({
        path: `/projects/${projectUid}/tables/${tableUid}/records/fetch`,
        method: "POST",
        body: data,
        type: ContentType.Json,
        format: "json",
        ...params,
      }),

    /**
     * @description Filter, group and sort the records of the table. Formula fields cannot be queried.
     *
     * @name QueryRecords
     * @summary Query records
     * @request POST:/projects/{projectUID}/tables/{tableUID}/records/query
     */
    queryRecords: (
      projectUid: string,
      tableUid: string,
      data: QueryRecords,
      params: RequestParams = {},
    ) =>
      this.request<QueryRecordsData, string>({
        path: `/projects/${projectUid}/tables/${tableUid}/records/query`,
        method: "POST",
        body: data,
        type: ContentType.Json,
        format: "json",
        ...params,
      }),

    /**
     * No description
     *
     * @name GetRecord
     * @summary Get a record
     * @request GET:/projects/{projectUID}/tables/{tableUID}/records/{recordUID}
     */
    getRecord: (
      projectUid: string,
      tableUid: string,
      recordUid: string,
      params: RequestParams = {},
    ) =>
      this.request<GetRecordData, string>({
        path: `/projects/${projectUid}/tables/${tableUid}/records/${recordUid}`,
        method: "GET",
        format: "json",
        ...params,
      }),

    /**
     * No description
     *
     * @name UpdateRecord
     * @summary Update a record
     * @request PUT:/projects/{projectUID}/tables/{tableUID}/records/{recordUID}
     */
    updateRecord: (
      projectUid: string,
      tableUid: string,
      recordUid: string,
      data: UpdateRecord,
      params: RequestParams = {},
    ) =>
      this.request<UpdateRecordData, string>({
        path: `/projects/${projectUid}/tables/${tableUid}/records/${recordUid}`,
        method: "PUT",
        body: data,
        type: ContentType.Json,
        ...params,
      }),

    /**
     * No description
     *
     * @name DeleteRecord
     * @summary Delete a record
     * @request DELETE:/projects/{projectUID}/tables/{tableUID}/records/{recordUID}
     */
    deleteRecord: (
      projectUid: string,
      tableUid: string,
      recordUid: string,
      params: RequestParams = {},
    ) =>
      this.request<DeleteRecordData, string>({
        path: `/projects/${projectUid}/tables/${tableUid}/records/${recordUid}`,
        method: "DELETE",
        ...params,
      }),

    /**
     * @description List the cells of the table being generated by the field shortcuts or failed to.
     *
     * @name ListShortcutJobs
     * @summary List the shortcut jobs
     * @request GET:/projects/{projectUID}/tables/{tableUID}/shortcut-jobs
     */
    listShortcutJobs: (
      projectUid: string,
      tableUid: string,
      params: RequestParams = {},
    ) =>
      this.request<ListShortcutJobsData, string>({
        path: `/projects/${projectUid}/tables/${tableUid}/shortcut-jobs`,
        method: "GET",
        format: "json",
        ...params,
      }),

    /**
     * @description Execute the unsaved shortcut config of the field on at most 3 records, the results are not written back.
     *
     * @name PreviewFieldShortcut
     * @summary Preview a field shortcut
     * @request POST:/projects/{projectUID}/tables/{tableUID}/shortcuts/preview
     */
    previewFieldShortcut: (
      projectUid: string,
      tableUid: string,
      data: PreviewFieldShortcut,
      params: RequestParams = {},
    ) =>
      this.request<PreviewFieldShortcutData, string>({
        path: `/projects/${projectUid}/tables/${tableUid}/shortcuts/preview`,
        method: "POST",
        body: data,
        type: ContentType.Json,
        format: "json",
        ...params,
      }),

    /**
     * @description Return the fields, views and all the records of the table consistently at the latest revision.
     *
     * @name GetTableSnapshot
     * @summary Get the table snapshot
     * @request GET:/projects/{projectUID}/tables/{tableUID}/snapshot
     */
    getTableSnapshot: (
      projectUid: string,
      tableUid: string,
      params: RequestParams = {},
    ) =>
      this.request<GetTableSnapshotData, string>({
        path: `/projects/${projectUid}/tables/${tableUid}/snapshot`,
        method: "GET",
        format: "json",
        ...params,
      }),

    /**
     * No description
     *
     * @name ListViews
     * @summary List views
     * @request GET:/projects/{projectUID}/tables/{tableUID}/views
     */
    listViews: (
      projectUid: string,
      tableUid: string,
      params: RequestParams = {},
    ) =>
      this.request<ListViewsData, string>({
        path: `/projects/${projectUid}/tables/${tableUid}/views`,
        method: "GET",
        format: "json",
        ...params,
      }),

    /**
     * @description Upgrade to WebSocket to submit changesets and receive the changes of the subscribed tables and the online members. Messages are JSON `{type, reqId, data}`. Client: SUBSCRIBE, UNSUBSCRIBE, USER_CHANGES, PRESENCE, PING. Server: HELLO, SUBSCRIBED, ACCEPT_COMMIT, REJECT_COMMIT, NEW_CHANGES, MEMBERS, TABLES_CHANGED, PROJECT_CHANGED, PERMISSION_CHANGED, ERROR, PONG. The changesets of the viewers are rejected.
     *
     * @name Collaborate
     * @summary Collaborate on the project over WebSocket
     * @request GET:/projects/{projectUID}/ws
     */
    collaborate: (projectUid: string, params: RequestParams = {}) =>
      this.request<any, void | string>({
        path: `/projects/${projectUid}/ws`,
        method: "GET",
        ...params,
      }),
  };
  site = {
    /**
     * @description Public information used by the sign-in page, such as whether signing up is allowed.
     *
     * @name GetSiteInfo
     * @summary Get the site information
     * @request GET:/site
     */
    getSiteInfo: (params: RequestParams = {}) =>
      this.request<GetSiteInfoData, string>({
        path: `/site`,
        method: "GET",
        format: "json",
        ...params,
      }),
  };
}
