package collab

import (
	"context"
	"encoding/json"
	"sort"
	"sync"
	"time"

	"github.com/pkg/errors"
	"gorm.io/gorm"

	"github.com/wuhan005/sayrud/internal/db"
)

// Hub routes the messages between the clients connected to the same server instance.
//
// The changesets of a table are committed and broadcast under a per-table lock, so the subscribers receive them in revision order.
// NOTE: The hub is in memory, running multiple server instances requires a shared message bus such as Redis Pub/Sub.
type Hub struct {
	db *gorm.DB

	mu       sync.Mutex
	projects map[string]map[*Client]struct{}
	locks    map[int64]*sync.Mutex

	shortcuts ShortcutHooks
}

// SetShortcutHooks connects the field shortcuts, it must be called before serving.
func (h *Hub) SetShortcutHooks(hooks ShortcutHooks) {
	h.shortcuts = hooks
}

func NewHub(gormDB *gorm.DB) *Hub {
	return &Hub{
		db:       gormDB,
		projects: make(map[string]map[*Client]struct{}),
		locks:    make(map[int64]*sync.Mutex),
	}
}

func (h *Hub) tableLock(tableID int64) *sync.Mutex {
	h.mu.Lock()
	defer h.mu.Unlock()
	lock, ok := h.locks[tableID]
	if !ok {
		lock = &sync.Mutex{}
		h.locks[tableID] = lock
	}
	return lock
}

func (h *Hub) register(c *Client) {
	h.mu.Lock()
	clients, ok := h.projects[c.projectUID]
	if !ok {
		clients = make(map[*Client]struct{})
		h.projects[c.projectUID] = clients
	}
	clients[c] = struct{}{}
	h.mu.Unlock()

	c.send(newMessage(MessageHello, 0, helloData{ClientID: c.member.ClientID}))
	h.broadcastMembers(c.projectUID)
}

func (h *Hub) unregister(c *Client) {
	h.mu.Lock()
	delete(h.projects[c.projectUID], c)
	if len(h.projects[c.projectUID]) == 0 {
		delete(h.projects, c.projectUID)
	}
	h.mu.Unlock()

	h.broadcastMembers(c.projectUID)
}

func (h *Hub) clients(projectUID string) []*Client {
	h.mu.Lock()
	defer h.mu.Unlock()
	clients := make([]*Client, 0, len(h.projects[projectUID]))
	for c := range h.projects[projectUID] {
		clients = append(clients, c)
	}
	return clients
}

func (h *Hub) broadcastMembers(projectUID string) {
	// Snapshot and queue under the same lock so an older presence broadcast can not follow an avatar update.
	h.mu.Lock()
	defer h.mu.Unlock()
	clients := h.projects[projectUID]
	members := make([]Member, 0, len(clients))
	for c := range clients {
		members = append(members, c.presence())
	}
	sort.Slice(members, func(i, j int) bool { return members[i].ClientID < members[j].ClientID })

	message := newMessage(MessageMembers, 0, membersData{Members: members})
	for c := range clients {
		c.send(message)
	}
}

// UpdateUserAvatar refreshes all connections of the user, ignoring an older concurrent update.
func (h *Hub) UpdateUserAvatar(userID int64, avatarURL string, updatedAt time.Time) {
	var projects []string

	h.mu.Lock()
	for projectUID, clients := range h.projects {
		changed := false
		for c := range clients {
			if c.userID != userID {
				continue
			}

			c.mu.Lock()
			if !c.avatarUpdatedAt.After(updatedAt) {
				c.member.AvatarURL = avatarURL
				c.avatarUpdatedAt = updatedAt
				changed = true
			}
			c.mu.Unlock()
		}

		if changed {
			projects = append(projects, projectUID)
		}
	}
	h.mu.Unlock()

	for _, projectUID := range projects {
		h.broadcastMembers(projectUID)
	}
}

// subscribe subscribes the client to the table changes, and returns the latest revision of the table.
func (h *Hub) subscribe(ctx context.Context, c *Client, table *db.SLTable) (int64, error) {
	// Hold the table lock so no changeset is committed between reading the revision and starting to receive the broadcasts.
	lock := h.tableLock(table.ID)
	lock.Lock()
	defer lock.Unlock()

	latest, err := db.SLTables.GetByID(ctx, table.ID)
	if err != nil {
		return 0, errors.Wrap(err, "get table")
	}
	c.subscribe(table.UID)
	return latest.Rev, nil
}

// CommitResult is the result of committing a changeset.
type CommitResult struct {
	Rev int64
	// Duplicate reports the changeset with the same signature has been committed before, e.g. resent after reconnecting.
	Duplicate bool
}

// Commit applies the operations to the table and broadcasts the accepted changeset to the subscribers except the sender.
// If the server changes other data when applying, e.g. converting the values of a field, a server changeset with the dirty
// scope is committed right after it and broadcast to all the subscribers.
//
// onAccept is called before broadcasting, so the sender receives the acceptance before the following changesets.
// It returns *OperationError if the changeset is rejected.
func (h *Hub) Commit(ctx context.Context, project *db.Project, table *db.SLTable, sender *Client, signature string, operations []Operation, onAccept func(CommitResult)) error {
	_, err := h.commit(ctx, project, table, sender, signature, operations, nil, onAccept)
	return err
}

// CommitServer applies the operations generated by the server, e.g. writing back the results of the field shortcuts, and broadcasts
// them to all the subscribers. guard runs first in the same transaction, the changeset is skipped if it returns false.
// It reports whether the changeset is committed.
func (h *Hub) CommitServer(ctx context.Context, project *db.Project, table *db.SLTable, operations []Operation, guard func(tx *gorm.DB) (bool, error)) (bool, error) {
	return h.commit(ctx, project, table, nil, "", operations, guard, func(CommitResult) {})
}

func (h *Hub) commit(ctx context.Context, project *db.Project, table *db.SLTable, sender *Client, signature string, operations []Operation, guard func(tx *gorm.DB) (bool, error), onAccept func(CommitResult)) (bool, error) {
	lock := h.tableLock(table.ID)
	lock.Lock()
	defer lock.Unlock()

	if signature != "" {
		changeset, err := db.SLChangesets.GetBySignature(ctx, table.ID, signature)
		if err == nil {
			onAccept(CommitResult{Rev: changeset.Rev, Duplicate: true})
			return false, nil
		} else if !errors.Is(err, db.ErrSLChangesetNotFound) {
			return false, errors.Wrap(err, "get changeset by signature")
		}
	}

	var clientID string
	if sender != nil {
		clientID = sender.member.ClientID
	}

	var changesets []*Changeset
	var change Change
	errSkipped := errors.New("skipped by the guard")
	if err := h.db.Transaction(func(tx *gorm.DB) error {
		if guard != nil {
			ok, err := guard(tx)
			if err != nil {
				return err
			}
			if !ok {
				return errSkipped
			}
		}

		a, err := newApplier(ctx, tx, table, sender.boolText, h.shortcuts)
		if err != nil {
			return err
		}
		applied, err := a.apply(operations)
		if err != nil {
			return err
		}

		changeset, err := appendChangeset(ctx, tx, table, signature, clientID, applied)
		if err != nil {
			return err
		}
		changesets = append(changesets, changeset)

		if !a.dirty.IsEmpty() {
			dirty := a.dirty
			changeset, err := appendChangeset(ctx, tx, table, "", "", []Operation{{
				Command: "Refresh",
				Actions: []Action{{Action: ActionDirty, Dirty: &dirty}},
			}})
			if err != nil {
				return err
			}
			changesets = append(changesets, changeset)
		}
		// The tables without shortcuts have nothing to regenerate.
		if a.hasShortcuts() || len(a.change.RemovedShortcuts) > 0 {
			change = a.change
		}
		return nil
	}); err != nil {
		if errors.Is(err, errSkipped) {
			return false, nil
		}
		return false, err
	}

	onAccept(CommitResult{Rev: changesets[0].Rev})
	for i, changeset := range changesets {
		h.broadcastChangeset(project, changeset, ternary(i == 0, sender, nil))
	}
	h.NotifyChange(ctx, project, table, &change)
	h.notifyOptionReferences(ctx, project, table, operations)
	return true, nil
}

// NotifyChange tells the field shortcuts the data is changed, it runs in the background so the caller is not blocked.
func (h *Hub) NotifyChange(ctx context.Context, project *db.Project, table *db.SLTable, change *Change) {
	if h.shortcuts == nil || change.IsEmpty() {
		return
	}
	go h.shortcuts.ShortcutsChanged(context.WithoutCancel(ctx), project, table, change)
}

// NotifyTable sends the message to the subscribers of the table, build returns the data in the language of each subscriber.
func (h *Hub) NotifyTable(projectUID, tableUID, messageType string, build func(tr func(key string, args ...interface{}) string) interface{}) {
	for _, c := range h.clients(projectUID) {
		if c.subscribed(tableUID) {
			c.send(newMessage(messageType, 0, build(c.tr)))
		}
	}
}

// NotifyDirty commits a server changeset telling the subscribers to reload the data, which is changed out of the changesets,
// e.g. by the REST API.
func (h *Hub) NotifyDirty(ctx context.Context, project *db.Project, table *db.SLTable, scope DirtyScope) error {
	lock := h.tableLock(table.ID)
	lock.Lock()
	defer lock.Unlock()

	var changeset *Changeset
	if err := h.db.Transaction(func(tx *gorm.DB) error {
		var err error
		changeset, err = appendChangeset(ctx, tx, table, "", "", []Operation{{
			Command: "Refresh",
			Actions: []Action{{Action: ActionDirty, Dirty: &scope}},
		}})
		return err
	}); err != nil {
		return err
	}
	h.broadcastChangeset(project, changeset, nil)
	h.notifyOptionReferences(ctx, project, table, changeset.Operations)
	return nil
}

func appendChangeset(ctx context.Context, tx *gorm.DB, table *db.SLTable, signature, clientID string, operations []Operation) (*Changeset, error) {
	rev, err := db.NewSLTablesStore(tx).IncreaseRev(ctx, table.ID)
	if err != nil {
		return nil, errors.Wrap(err, "increase rev")
	}
	raw, err := json.Marshal(operations)
	if err != nil {
		return nil, errors.Wrap(err, "encode operations")
	}
	if _, err := db.NewSLChangesetsStore(tx).Create(ctx, db.CreateSLChangesetOptions{
		SLTableID:  table.ID,
		Rev:        rev,
		Signature:  signature,
		ClientID:   clientID,
		Operations: raw,
	}); err != nil {
		return nil, errors.Wrap(err, "create changeset")
	}
	return &Changeset{
		TableUID:   table.UID,
		Rev:        rev,
		Signature:  signature,
		ClientID:   clientID,
		Operations: operations,
	}, nil
}

func (h *Hub) broadcastChangeset(project *db.Project, changeset *Changeset, except *Client) {
	message := newMessage(MessageNewChanges, 0, changeset)
	for _, c := range h.clients(project.UID) {
		if c != except && c.subscribed(changeset.TableUID) {
			c.send(message)
		}
	}
}

// NotifyProject tells the clients of the project to reload the project or its table list.
func (h *Hub) NotifyProject(projectUID, messageType string) {
	message := newMessage(messageType, 0, projectEventData{ProjectUID: projectUID})
	for _, c := range h.clients(projectUID) {
		c.send(message)
	}
}

// SetUserRole applies the new role of the user to its connections of the project and notifies them.
// An empty role means the user is removed from the project, and the connections are closed after the notification.
func (h *Hub) SetUserRole(projectUID string, userID int64, role db.ProjectRole) {
	message := newMessage(MessagePermissionChanged, 0, permissionChangedData{ProjectUID: projectUID, Role: string(role)})
	for _, c := range h.clients(projectUID) {
		if c.userID != userID {
			continue
		}
		c.mu.Lock()
		c.canEdit = role.AtLeast(db.ProjectRoleEditor)
		c.mu.Unlock()
		c.send(message)
		if role == "" {
			c.close()
		}
	}
}

// DisconnectUser closes the connections of the user on all projects.
func (h *Hub) DisconnectUser(userID int64) {
	h.mu.Lock()
	var targets []*Client
	for _, clients := range h.projects {
		for c := range clients {
			if c.userID == userID {
				targets = append(targets, c)
			}
		}
	}
	h.mu.Unlock()
	for _, c := range targets {
		c.close()
	}
}

func ternary[T any](condition bool, a, b T) T {
	if condition {
		return a
	}
	return b
}
