// Package collab implements the collaborative editing of tables: clients submit changesets of business operations over WebSocket,
// the server applies them in order with a per-table revision, and broadcasts the accepted changesets to the other subscribers.
package collab

import (
	"regexp"
)

// Changeset is a batch of operations applied to a table atomically.
type Changeset struct {
	TableUID string `json:"tableUID"`
	Rev      int64  `json:"rev"`
	// Signature is generated by the submitting client to recognize its own changeset, it is empty for the changesets generated by the server.
	Signature string `json:"signature"`
	// ClientID is the connection that submits the changeset, it is empty for the changesets generated by the server.
	ClientID   string      `json:"clientId"`
	Operations []Operation `json:"operations"`
} // @name Changeset

// Operation is a user command, e.g. SetRecord, which consists of one or more actions.
type Operation struct {
	Command string   `json:"command"`
	Actions []Action `json:"actions"`
} // @name Operation

const (
	ActionAddRecord     = "record.add"
	ActionSetRecord     = "record.set"
	ActionDeleteRecords = "record.delete"
	ActionAddField      = "field.add"
	ActionSetField      = "field.set"
	ActionSetFieldType  = "field.setType"
	ActionMoveField     = "field.move"
	ActionDeleteField   = "field.delete"
	ActionAddView       = "view.add"
	ActionSetView       = "view.set"
	ActionMoveView      = "view.move"
	ActionDeleteView    = "view.delete"
	// ActionDirty is only generated by the server, it tells the clients to reload the data changed by the server.
	ActionDirty = "table.dirty"
)

// Action is the smallest change of a table, it locates the resources by UID instead of position, so concurrent actions rarely conflict.
type Action struct {
	Action string `json:"action" enums:"record.add,record.set,record.delete,field.add,field.set,field.setType,field.move,field.delete,view.add,view.set,view.move,view.delete,table.dirty"`
	// RecordUID is generated by the client for record.add.
	RecordUID  string   `json:"recordUID,omitempty"`
	RecordUIDs []string `json:"recordUIDs,omitempty"`
	// FieldUID is generated by the client for field.add.
	FieldUID string `json:"fieldUID,omitempty"`
	// ViewUID is generated by the client for view.add.
	ViewUID string `json:"viewUID,omitempty"`
	// Index is the zero-based position for field.move / view.move, and the optional insert position for field.add / view.add.
	Index *int `json:"index,omitempty"`
	// Values are the cell values keyed by field UID for record.add / record.set, a null value clears the cell.
	Values map[string]interface{} `json:"values,omitempty"`
	Field  *FieldAttrs            `json:"field,omitempty"`
	View   *ViewAttrs             `json:"view,omitempty"`
	Dirty  *DirtyScope            `json:"dirty,omitempty"`
} // @name Action

// FieldAttrs are the field properties for field.add / field.set / field.setType, the null ones are unchanged.
type FieldAttrs struct {
	Label    *string                `json:"label,omitempty"`
	Type     *string                `json:"type,omitempty" enums:"text,single_select,multi_select,datetime,number,checkbox,formula"`
	Metadata map[string]interface{} `json:"metadata,omitempty"`
} // @name FieldAttrs

// ViewAttrs are the view properties for view.add / view.set, the null ones are unchanged.
type ViewAttrs struct {
	Name   *string                `json:"name,omitempty"`
	Type   *string                `json:"type,omitempty" enums:"grid,kanban,gallery,form"`
	Config map[string]interface{} `json:"config,omitempty"`
} // @name ViewAttrs

// DirtyScope is the data changed by the server, which the clients should reload.
type DirtyScope struct {
	Fields     bool     `json:"fields,omitempty"`
	Views      bool     `json:"views,omitempty"`
	AllRecords bool     `json:"allRecords,omitempty"`
	Records    []string `json:"records,omitempty"`
} // @name DirtyScope

func (s *DirtyScope) IsEmpty() bool {
	return !s.Fields && !s.Views && !s.AllRecords && len(s.Records) == 0
}

func (s *DirtyScope) addRecords(uids ...string) {
	if s.AllRecords {
		return
	}
	s.Records = append(s.Records, uids...)
	// Reloading all the records is cheaper than listing too many UIDs.
	if len(s.Records) > 500 {
		s.AllRecords = true
		s.Records = nil
	}
}

var (
	recordUIDPattern = regexp.MustCompile(`^rec[A-Za-z0-9]{11}$`)
	fieldUIDPattern  = regexp.MustCompile(`^fld[A-Za-z0-9]{7}$`)
	viewUIDPattern   = regexp.MustCompile(`^viw[A-Za-z0-9]{10}$`)
)
