package dto

import (
	"encoding/json"
)

// AIAdviceResp is the table design advice generated by AI.
type AIAdviceResp struct {
	// Raw is the raw output of the model.
	Raw    string `json:"raw"`
	Action string `json:"action"`
	// ActionJSON is the structured payload of the action, which can be passed to the apply API as is.
	ActionJSON  json.RawMessage `json:"actionJson" swaggertype:"object"`
	Description string          `json:"description"`
} // @name AIAdviceResp
