package dto

import (
	"encoding/json"
)

// AIAdviceResp is the table design advice generated by AI.
type AIAdviceResp struct {
	// Raw is the raw output of the model.
	Raw    string `json:"raw"`
	Action string `json:"action"`
	// ActionJSON is the structured payload of the action, which can be passed to the apply API as is.
	ActionJSON  json.RawMessage `json:"actionJson" swaggertype:"object"`
	Description string          `json:"description"`
} // @name AIAdviceResp

// AdminAISettings is the AI model used by the AI field shortcuts, the API key is not returned.
type AdminAISettings struct {
	// Enabled reports whether the AI field shortcuts can be executed.
	Enabled bool `json:"enabled"`
	// BaseURL is the API root including the version, e.g. https://api.openai.com/v1.
	BaseURL string `json:"baseURL"`
	// Model is the name of the model to call.
	Model string `json:"model"`
	// TimeoutSeconds is the timeout of a completion request.
	TimeoutSeconds int `json:"timeoutSeconds"`
	// APIKeySet reports whether an API key is saved and readable.
	APIKeySet bool `json:"apiKeySet"`
	// SecretsReady is false if auth.secret_key is not configured, the API key can not be saved.
	SecretsReady bool `json:"secretsReady"`
} // @name AdminAISettings

// TestAISettingsResp is the reply of the model to the test message.
type TestAISettingsResp struct {
	// Reply is the content returned by the model, truncated to 500 characters.
	Reply string `json:"reply"`
	// DurationMs is the time of the request in milliseconds.
	DurationMs int64 `json:"durationMs"`
} // @name TestAISettingsResp
