package dto

import (
	"time"

	"github.com/wuhan005/sayrud/internal/db"
)

// FieldShortcutManifest describes a field shortcut for the field editor to render the configuration form.
type FieldShortcutManifest struct {
	// ID is the UID of a custom shortcut.
	ID string `json:"id"`
	// Kind is how the shortcut is executed, by a custom script.
	Kind string `json:"kind" enums:"script"`
	// Name is shown in the field editor.
	Name string `json:"name"`
	// Description tells what the shortcut does.
	Description string `json:"description"`
	// ResultTypes are the types of the fields the shortcut can be attached to.
	ResultTypes []string `json:"resultTypes"`
	// FormItems are the inputs to configure in the field editor.
	FormItems []db.ShortcutFormItem `json:"formItems"`
	// AIEnabled reports whether the script is allowed to use the globally configured AI model.
	AIEnabled bool `json:"aiEnabled"`
	// Available is false if the shortcut is disabled or its AI configuration is unavailable.
	Available bool `json:"available"`
} // @name FieldShortcutManifest

// ShortcutJob is a cell being generated by the shortcut of its field, or failed to.
type ShortcutJob struct {
	// FieldUID is the field of the cell.
	FieldUID string `json:"fieldUID"`
	// RecordUID is the record of the cell.
	RecordUID string `json:"recordUID"`
	// Status is done when the job is removed, which is only sent over WebSocket.
	Status string `json:"status" enums:"pending,running,failed,done"`
	// Error is the reason of the failure, or of the last attempt of a pending retry.
	Error string `json:"error,omitempty"`
} // @name ShortcutJob

// ShortcutJobsMessage is the data of the SHORTCUT_JOBS WebSocket message.
type ShortcutJobsMessage struct {
	// TableUID is the table of the jobs.
	TableUID string `json:"tableUID"`
	// Reload tells the client to fetch all the jobs of the table instead, e.g. too many cells are changed.
	Reload bool `json:"reload,omitempty"`
	// Jobs are the changed jobs, empty if Reload is true.
	Jobs []*ShortcutJob `json:"jobs"`
} // @name ShortcutJobsMessage

// RunFieldShortcutResp is the result of queuing the cells to generate.
type RunFieldShortcutResp struct {
	// Count is the number of the cells queued.
	Count int `json:"count"`
} // @name RunFieldShortcutResp

// ShortcutPreview is the result of the shortcut on a record, which is not written back.
type ShortcutPreview struct {
	// RecordUID is the record previewed.
	RecordUID string `json:"recordUID"`
	// Value is the cell value of the field, null if empty or failed.
	Value interface{} `json:"value,omitempty" swaggertype:"object"`
	// Error is the reason of the failure, empty if succeeded.
	Error string `json:"error,omitempty"`
} // @name ShortcutPreview

// AdminFieldShortcut is a custom field shortcut for the admins, the credential values are not returned.
type AdminFieldShortcut struct {
	// UID is the identifier the fields refer to the shortcut by.
	UID string `json:"uid"`
	// Name is shown in the field editor.
	Name string `json:"name"`
	// Description tells the members what the shortcut does.
	Description string `json:"description"`
	// ResultType is the type of the fields the shortcut can be attached to.
	ResultType string `json:"resultType"`
	// Code defines `async function execute(params, context)` returning the cell value, with context.ai.complete using the global model when AIEnabled.
	Code string `json:"code"`
	// AIEnabled allows the script to call the globally configured AI model.
	AIEnabled bool `json:"aiEnabled"`
	// FormItems are the inputs configured in the field editor and passed to execute as the params.
	FormItems []db.ShortcutFormItem `json:"formItems"`
	// Domains are the hosts the script can fetch, including their subdomains.
	Domains []string `json:"domains"`
	// Credentials are the credentials the script can use when fetching.
	Credentials []*AdminCredential `json:"credentials"`
	// TimeoutSeconds is the time limit of an execution.
	TimeoutSeconds int `json:"timeoutSeconds"`
	// Enabled reports whether the members can attach and execute the shortcut.
	Enabled bool `json:"enabled"`
	// UsedBy is the number of the fields using the shortcut.
	UsedBy int64 `json:"usedBy"`
	// CreatedAt is the time the shortcut was created.
	CreatedAt time.Time `json:"createdAt"`
	// UpdatedAt is the time the shortcut was last updated.
	UpdatedAt time.Time `json:"updatedAt"`
} // @name AdminFieldShortcut

// AdminCredential is a credential of a custom shortcut, HasValue reports whether its value is saved.
type AdminCredential struct {
	Key      string `json:"key"`
	Type     string `json:"type" enums:"bearer,header,query"`
	Name     string `json:"name,omitempty"`
	HasValue bool   `json:"hasValue"`
} // @name AdminCredential

// ToAdminFieldShortcut converts the custom shortcut, keys are the credentials with saved values.
func ToAdminFieldShortcut(s *db.CustomFieldShortcut, valueKeys map[string]bool, usedBy int64) *AdminFieldShortcut {
	credentials := make([]*AdminCredential, 0, len(s.Credentials.Data()))
	for _, c := range s.Credentials.Data() {
		credentials = append(credentials, &AdminCredential{Key: c.Key, Type: string(c.Type), Name: c.Name, HasValue: valueKeys[c.Key]})
	}

	formItems := s.FormItems.Data()
	if formItems == nil {
		formItems = []db.ShortcutFormItem{}
	}
	domains := s.Domains.Data()
	if domains == nil {
		domains = []string{}
	}

	return &AdminFieldShortcut{
		UID:            s.UID,
		Name:           s.Name,
		Description:    s.Description,
		ResultType:     string(s.ResultType),
		Code:           s.Code,
		AIEnabled:      s.AIEnabled,
		FormItems:      formItems,
		Domains:        domains,
		Credentials:    credentials,
		TimeoutSeconds: s.TimeoutSeconds,
		Enabled:        s.Enabled,
		UsedBy:         usedBy,
		CreatedAt:      s.CreatedAt,
		UpdatedAt:      s.UpdatedAt,
	}
}

// TestFieldShortcutResp is the result of a test run of a custom shortcut.
type TestFieldShortcutResp struct {
	// Value is the value returned by execute, before converting to the cell value.
	Value interface{} `json:"value,omitempty" swaggertype:"object"`
	// CellValue is the value converted for a field of the result type, select fields are not converted as there are no options.
	CellValue interface{} `json:"cellValue,omitempty" swaggertype:"object"`
	// Error is the reason of the failure, empty if succeeded.
	Error string `json:"error,omitempty"`
	// Logs are the lines printed by console and context.log, with the credential values redacted.
	Logs []string `json:"logs"`
	// DurationMs is the time of the run in milliseconds.
	DurationMs int64 `json:"durationMs"`
} // @name TestFieldShortcutResp
