// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/profile": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Get the profile of the signed-in user",
                "operationId": "getProfile",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Profile"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/projects": {
            "get": {
                "description": "List the projects owned by the signed-in user, with the number of tables in each project.",
                "produces": [
                    "application/json"
                ],
                "summary": "List projects",
                "operationId": "listProjects",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number, starting from 1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size, defaults to 20",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ListProjectsResp"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a project owned by the signed-in user, along with its Postgres schema.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Create a project",
                "operationId": "createProject",
                "parameters": [
                    {
                        "description": "Project to create",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/CreateProject"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Project"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "Schema name already exists",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/projects/{projectUID}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Get a project",
                "operationId": "getProject",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project UID",
                        "name": "projectUID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Project"
                        }
                    },
                    "403": {
                        "description": "Permission denied",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Project not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Update a project",
                "operationId": "updateProject",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project UID",
                        "name": "projectUID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Project properties",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/UpdateProject"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Permission denied",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Project not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete the project and drop its Postgres schema.",
                "produces": [
                    "application/json"
                ],
                "summary": "Delete a project",
                "operationId": "deleteProject",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project UID",
                        "name": "projectUID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "403": {
                        "description": "Permission denied",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Project not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/projects/{projectUID}/ai/advice": {
            "post": {
                "description": "Generate the advice of the action by AI from the conversation messages.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Get table design advice from AI",
                "operationId": "aiAdvice",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project UID",
                        "name": "projectUID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Action and conversation messages",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/AIAdvice"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/AIAdviceResp"
                        }
                    },
                    "403": {
                        "description": "Permission denied",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Project not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/projects/{projectUID}/ai/apply": {
            "post": {
                "description": "Apply the actionJson returned by the advice API, e.g. create the advised tables.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Apply the AI advice",
                "operationId": "aiApply",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project UID",
                        "name": "projectUID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Action to apply",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/AIApply"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Invalid action or payload",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Permission denied",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Project not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/projects/{projectUID}/tables": {
            "get": {
                "description": "List the tables of the project, with the number of records in each table.",
                "produces": [
                    "application/json"
                ],
                "summary": "List tables",
                "operationId": "listTables",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project UID",
                        "name": "projectUID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Page number, starting from 1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size, defaults to 20",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ListTablesResp"
                        }
                    },
                    "403": {
                        "description": "Permission denied",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Project not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Create a table",
                "operationId": "createTable",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project UID",
                        "name": "projectUID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Table to create",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/CreateTable"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/SLTable"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Permission denied",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Project not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "Table already exists",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/projects/{projectUID}/tables/types": {
            "get": {
                "description": "Return the labels of all the field types, keyed by field type.",
                "produces": [
                    "application/json"
                ],
                "summary": "List field types",
                "operationId": "listFieldTypes",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project UID",
                        "name": "projectUID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Permission denied",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Project not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/projects/{projectUID}/tables/{tableUID}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Get a table",
                "operationId": "getTable",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project UID",
                        "name": "projectUID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Table UID",
                        "name": "tableUID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/SLTable"
                        }
                    },
                    "403": {
                        "description": "Permission denied",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Project or table not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Update a table",
                "operationId": "updateTable",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project UID",
                        "name": "projectUID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Table UID",
                        "name": "tableUID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Table properties",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/UpdateTable"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Permission denied",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Project or table not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "summary": "Delete a table",
                "operationId": "deleteTable",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project UID",
                        "name": "projectUID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Table UID",
                        "name": "tableUID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "403": {
                        "description": "Permission denied",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Project or table not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/projects/{projectUID}/tables/{tableUID}/fields": {
            "get": {
                "description": "List all the fields of the table, ordered by position.",
                "produces": [
                    "application/json"
                ],
                "summary": "List fields",
                "operationId": "listFields",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project UID",
                        "name": "projectUID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Table UID",
                        "name": "tableUID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/SLField"
                            }
                        }
                    },
                    "403": {
                        "description": "Permission denied",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Project or table not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Create fields in batch, which are appended to the end of the table.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Create fields",
                "operationId": "createFields",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project UID",
                        "name": "projectUID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Table UID",
                        "name": "tableUID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Fields to create",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/CreateFields"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/SLField"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid label or type",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Permission denied",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Project or table not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "Field label already exists",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/projects/{projectUID}/tables/{tableUID}/fields/{fieldUID}": {
            "put": {
                "description": "Update the label, type or metadata of the field. Existing record values are kept as is when the type changes.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Update a field",
                "operationId": "updateField",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project UID",
                        "name": "projectUID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Table UID",
                        "name": "tableUID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Field UID",
                        "name": "fieldUID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Field properties",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/UpdateField"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/SLField"
                        }
                    },
                    "400": {
                        "description": "Invalid label or type",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Permission denied",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Project, table or field not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "Field label already exists",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "summary": "Delete a field",
                "operationId": "deleteField",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project UID",
                        "name": "projectUID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Table UID",
                        "name": "tableUID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Field UID",
                        "name": "fieldUID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "403": {
                        "description": "Permission denied",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Project, table or field not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/projects/{projectUID}/tables/{tableUID}/fields/{fieldUID}/position": {
            "put": {
                "description": "Set the position of the field, the fields at or after the position are moved back by one.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Move a field",
                "operationId": "updateFieldPosition",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project UID",
                        "name": "projectUID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Table UID",
                        "name": "tableUID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Field UID",
                        "name": "fieldUID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Field position",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/UpdateFieldPosition"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "403": {
                        "description": "Permission denied",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Project, table or field not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/projects/{projectUID}/tables/{tableUID}/records": {
            "get": {
                "description": "List the records of the table, the newest first.",
                "produces": [
                    "application/json"
                ],
                "summary": "List records",
                "operationId": "listRecords",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project UID",
                        "name": "projectUID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Table UID",
                        "name": "tableUID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Maximum number of records, defaults to 20",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of records to skip",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ListRecordsResp"
                        }
                    },
                    "403": {
                        "description": "Permission denied",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Project or table not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Create a record",
                "operationId": "createRecord",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project UID",
                        "name": "projectUID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Table UID",
                        "name": "tableUID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Record to create",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/CreateRecord"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/SLRecord"
                        }
                    },
                    "400": {
                        "description": "Field not found or value mismatches the field type",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Permission denied",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Project or table not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/projects/{projectUID}/tables/{tableUID}/records/batch": {
            "post": {
                "description": "Create multiple records atomically, none is created if any data is invalid.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Create records in batch",
                "operationId": "batchCreateRecords",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project UID",
                        "name": "projectUID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Table UID",
                        "name": "tableUID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Records to create",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/BatchCreateRecords"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/SLRecord"
                            }
                        }
                    },
                    "400": {
                        "description": "Field not found or value mismatches the field type",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Permission denied",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Project or table not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/projects/{projectUID}/tables/{tableUID}/records/query": {
            "post": {
                "description": "Filter, group and sort the records of the table. Formula fields cannot be queried.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Query records",
                "operationId": "queryRecords",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project UID",
                        "name": "projectUID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Table UID",
                        "name": "tableUID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Query options",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/QueryRecords"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ListRecordsResp"
                        }
                    },
                    "400": {
                        "description": "Invalid field, operation, value or order",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Permission denied",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Project or table not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/projects/{projectUID}/tables/{tableUID}/records/{recordUID}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Get a record",
                "operationId": "getRecord",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project UID",
                        "name": "projectUID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Table UID",
                        "name": "tableUID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Record UID",
                        "name": "recordUID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/SLRecord"
                        }
                    },
                    "403": {
                        "description": "Permission denied",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Project, table or record not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Update a record",
                "operationId": "updateRecord",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project UID",
                        "name": "projectUID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Table UID",
                        "name": "tableUID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Record UID",
                        "name": "recordUID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Record data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/UpdateRecord"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Field not found or value mismatches the field type",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Permission denied",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Project, table or record not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "summary": "Delete a record",
                "operationId": "deleteRecord",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project UID",
                        "name": "projectUID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Table UID",
                        "name": "tableUID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Record UID",
                        "name": "recordUID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "403": {
                        "description": "Permission denied",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Project, table or record not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "AIAdvice": {
            "type": "object",
            "required": [
                "action",
                "messages"
            ],
            "properties": {
                "action": {
                    "type": "string",
                    "enum": [
                        "tables"
                    ]
                },
                "messages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/AIMessage"
                    }
                }
            }
        },
        "AIAdviceResp": {
            "type": "object",
            "required": [
                "action",
                "actionJson",
                "description",
                "raw"
            ],
            "properties": {
                "action": {
                    "type": "string"
                },
                "actionJson": {
                    "description": "ActionJSON is the structured payload of the action, which can be passed to the apply API as is.",
                    "type": "object"
                },
                "description": {
                    "type": "string"
                },
                "raw": {
                    "description": "Raw is the raw output of the model.",
                    "type": "string"
                }
            }
        },
        "AIApply": {
            "type": "object",
            "required": [
                "action",
                "actionJson"
            ],
            "properties": {
                "action": {
                    "type": "string",
                    "enum": [
                        "tables"
                    ]
                },
                "actionJson": {
                    "description": "ActionJson is the actionJson returned by the advice API.",
                    "type": "object"
                }
            }
        },
        "AIMessage": {
            "type": "object",
            "required": [
                "content",
                "role"
            ],
            "properties": {
                "content": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "BatchCreateRecords": {
            "type": "object",
            "required": [
                "data"
            ],
            "properties": {
                "data": {
                    "description": "Data is the list of cell values keyed by field UID, one item for each record.",
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": true
                    }
                }
            }
        },
        "CreateField": {
            "type": "object",
            "required": [
                "label",
                "type"
            ],
            "properties": {
                "label": {
                    "type": "string"
                },
                "metadata": {
                    "description": "Metadata is the type-specific configuration, e.g. select options or the formula expression.",
                    "type": "object",
                    "additionalProperties": true
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "text",
                        "single_select",
                        "multi_select",
                        "datetime",
                        "number",
                        "checkbox",
                        "formula"
                    ]
                }
            }
        },
        "CreateFields": {
            "type": "object",
            "required": [
                "fields"
            ],
            "properties": {
                "fields": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/CreateField"
                    }
                }
            }
        },
        "CreateProject": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string"
                },
                "schemaName": {
                    "description": "SchemaName is the Postgres schema of the project, a random one is generated if empty.",
                    "type": "string"
                }
            }
        },
        "CreateRecord": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "Data is the cell values keyed by field UID.",
                    "type": "object",
                    "additionalProperties": true
                }
            }
        },
        "CreateTable": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "ListProjectsResp": {
            "type": "object",
            "required": [
                "projects",
                "total"
            ],
            "properties": {
                "projects": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ProjectListItem"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "ListRecordsResp": {
            "type": "object",
            "required": [
                "records",
                "total"
            ],
            "properties": {
                "records": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/SLRecord"
                    }
                },
                "total": {
                    "description": "Total is the number of records matching the query, regardless of limit and offset.",
                    "type": "integer"
                }
            }
        },
        "ListTablesResp": {
            "type": "object",
            "required": [
                "tables",
                "total"
            ],
            "properties": {
                "tables": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/TableListItem"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "Profile": {
            "type": "object",
            "required": [
                "email",
                "emailMd5",
                "userName"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "emailMd5": {
                    "type": "string"
                },
                "userName": {
                    "type": "string"
                }
            }
        },
        "Project": {
            "type": "object",
            "required": [
                "createdAt",
                "name",
                "schemaName",
                "uid",
                "updatedAt"
            ],
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "schemaName": {
                    "type": "string"
                },
                "uid": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "ProjectListItem": {
            "type": "object",
            "required": [
                "createdAt",
                "name",
                "schemaName",
                "tableCount",
                "uid",
                "updatedAt"
            ],
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "schemaName": {
                    "type": "string"
                },
                "tableCount": {
                    "type": "integer"
                },
                "uid": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "QueryRecords": {
            "type": "object",
            "properties": {
                "filter": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/QueryRecordsFilter"
                    }
                },
                "group": {
                    "description": "Group sorts the records by the field values before Order, so records in the same group are adjacent.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/QueryRecordsGroup"
                    }
                },
                "limit": {
                    "description": "Limit defaults to 20 when it is not positive.",
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "order": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/QueryRecordsSort"
                    }
                }
            }
        },
        "QueryRecordsFilter": {
            "type": "object",
            "required": [
                "fieldUID",
                "operation",
                "value"
            ],
            "properties": {
                "fieldUID": {
                    "type": "string"
                },
                "operation": {
                    "type": "string",
                    "enum": [
                        "eq",
                        "neq",
                        "gt",
                        "lt",
                        "gte",
                        "lte",
                        "in",
                        "nin",
                        "like"
                    ]
                },
                "value": {
                    "description": "Value is a JSON array (e.g. ` + "`" + `[\"a\",\"b\"]` + "`" + `) for in / nin, and a single value for other operations.",
                    "type": "string"
                }
            }
        },
        "QueryRecordsGroup": {
            "type": "object",
            "required": [
                "fieldUID"
            ],
            "properties": {
                "fieldUID": {
                    "type": "string"
                }
            }
        },
        "QueryRecordsSort": {
            "type": "object",
            "required": [
                "fieldUID"
            ],
            "properties": {
                "fieldUID": {
                    "type": "string"
                },
                "order": {
                    "type": "string",
                    "enum": [
                        "asc",
                        "desc"
                    ]
                }
            }
        },
        "SLField": {
            "type": "object",
            "required": [
                "createdAt",
                "label",
                "metadata",
                "position",
                "tableUID",
                "type",
                "uid",
                "updatedAt"
            ],
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                },
                "metadata": {
                    "description": "Metadata is the type-specific configuration, e.g. select options or the formula expression.",
                    "type": "object",
                    "additionalProperties": true
                },
                "position": {
                    "type": "integer"
                },
                "tableUID": {
                    "type": "string"
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "text",
                        "single_select",
                        "multi_select",
                        "datetime",
                        "number",
                        "checkbox",
                        "formula"
                    ]
                },
                "uid": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "SLRecord": {
            "type": "object",
            "required": [
                "createdAt",
                "data",
                "tableUID",
                "uid",
                "updatedAt"
            ],
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "data": {
                    "description": "Data is the cell values keyed by field UID.",
                    "type": "object",
                    "additionalProperties": true
                },
                "tableUID": {
                    "type": "string"
                },
                "uid": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "SLTable": {
            "type": "object",
            "required": [
                "createdAt",
                "name",
                "projectUID",
                "uid",
                "updatedAt"
            ],
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "projectUID": {
                    "type": "string"
                },
                "uid": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "TableListItem": {
            "type": "object",
            "required": [
                "count",
                "createdAt",
                "name",
                "projectUID",
                "uid",
                "updatedAt"
            ],
            "properties": {
                "count": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "projectUID": {
                    "type": "string"
                },
                "uid": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "UpdateField": {
            "type": "object",
            "properties": {
                "label": {
                    "type": "string"
                },
                "metadata": {
                    "description": "Metadata replaces the whole field configuration, it is required when the type changes.",
                    "type": "object",
                    "additionalProperties": true
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "text",
                        "single_select",
                        "multi_select",
                        "datetime",
                        "number",
                        "checkbox",
                        "formula"
                    ]
                }
            }
        },
        "UpdateFieldPosition": {
            "type": "object",
            "required": [
                "position"
            ],
            "properties": {
                "position": {
                    "description": "Position is the new position of the field, negative values are treated as 0.",
                    "type": "integer"
                }
            }
        },
        "UpdateProject": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "UpdateRecord": {
            "type": "object",
            "required": [
                "data"
            ],
            "properties": {
                "data": {
                    "description": "Data replaces all the cell values of the record, keyed by field UID.",
                    "type": "object",
                    "additionalProperties": true
                }
            }
        },
        "UpdateTable": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/_",
	Schemes:          []string{},
	Title:            "Sayrud API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
