package db

import (
	"context"
	"time"

	"github.com/pkg/errors"
	"github.com/thanhpk/randstr"
	"gorm.io/gorm"
)

var _ FilesStore = (*files)(nil)

// Files is the default instance of the FilesStore.
var Files FilesStore

// FilesStore is the persistent interface for the metadata of the uploaded files, their content is written by the storage package.
type FilesStore interface {
	// Create creates a file record, the UID is generated by the caller to build the storage path first.
	Create(ctx context.Context, opts CreateFileOptions) (*File, error)
	// GetByID returns the file with the given ID.
	// It returns ErrFileNotFound if the file does not exist.
	GetByID(ctx context.Context, id int64) (*File, error)
	// GetByUID returns the file with the given UID.
	// It returns ErrFileNotFound if the file does not exist.
	GetByUID(ctx context.Context, uid string) (*File, error)
	// DeleteByID deletes the file record with the given ID.
	// It returns ErrFileNotFound if the file does not exist.
	DeleteByID(ctx context.Context, id int64) error
}

func NewFilesStore(db *gorm.DB) FilesStore {
	return &files{db}
}

// File is a file uploaded to the storage.
type File struct {
	ID  int64  `gorm:"primarykey"`
	UID string `gorm:"uniqueIndex:idx_files_uid"`
	// Category is the business usage such as avatars and attachments, it is also the first directory of the storage path.
	Category string `gorm:"index"`
	// Storage is the storage type when written, local or s3.
	Storage string
	// Path is the relative path of the file in the storage.
	Path string
	// Name is the original file name when uploaded, it is used as the download file name.
	Name string
	Size int64
	// ContentType is sniffed from the file content.
	ContentType string
	SHA256      string `gorm:"column:sha256"`
	// UserID is the uploader.
	UserID    int64 `gorm:"index"`
	CreatedAt time.Time
}

// NewFileUID generates a file UID.
func NewFileUID() string {
	return "fil" + randstr.String(13)
}

type files struct {
	*gorm.DB
}

// CreateFileOptions are the options of creating a file record.
type CreateFileOptions struct {
	UID         string
	Category    string
	Storage     string
	Path        string
	Name        string
	Size        int64
	ContentType string
	SHA256      string
	UserID      int64
}

func (db *files) Create(ctx context.Context, opts CreateFileOptions) (*File, error) {
	file := &File{
		UID:         opts.UID,
		Category:    opts.Category,
		Storage:     opts.Storage,
		Path:        opts.Path,
		Name:        opts.Name,
		Size:        opts.Size,
		ContentType: opts.ContentType,
		SHA256:      opts.SHA256,
		UserID:      opts.UserID,
	}
	if err := db.WithContext(ctx).Create(file).Error; err != nil {
		return nil, errors.Wrap(err, "create file")
	}
	return file, nil
}

var ErrFileNotFound = errors.New("file does not exist")

func (db *files) GetByID(ctx context.Context, id int64) (*File, error) {
	return db.get(ctx, "id = ?", id)
}

func (db *files) GetByUID(ctx context.Context, uid string) (*File, error) {
	return db.get(ctx, "uid = ?", uid)
}

func (db *files) get(ctx context.Context, query string, arg interface{}) (*File, error) {
	var file File
	if err := db.WithContext(ctx).Where(query, arg).First(&file).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, ErrFileNotFound
		}
		return nil, err
	}
	return &file, nil
}

func (db *files) DeleteByID(ctx context.Context, id int64) error {
	result := db.WithContext(ctx).Where("id = ?", id).Delete(&File{})
	if result.Error != nil {
		return result.Error
	}
	if result.RowsAffected == 0 {
		return ErrFileNotFound
	}
	return nil
}
