package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/cockroachdb/errors"
	"gorm.io/datatypes"
	"gorm.io/gorm"
)

var _ SLChangesetsStore = (*slChangesets)(nil)

var SLChangesets SLChangesetsStore

// SLChangesetsStore stores the accepted changesets of the tables, which are used to replay the missing changes to the clients.
type SLChangesetsStore interface {
	Create(ctx context.Context, options CreateSLChangesetOptions) (*SLChangeset, error)
	GetBySignature(ctx context.Context, tableID int64, signature string) (*SLChangeset, error)
	// ListSince returns at most limit changesets of the table whose revision is greater than rev, in revision order.
	ListSince(ctx context.Context, tableID, rev int64, limit int) ([]*SLChangeset, error)
}

func NewSLChangesetsStore(db *gorm.DB) SLChangesetsStore {
	return &slChangesets{db}
}

// SLChangeset is a batch of operations applied to a table atomically, with a revision increasing by one for each table.
type SLChangeset struct {
	ID        int64 `gorm:"primarykey"`
	SLTableID int64 `gorm:"uniqueIndex:idx_sl_changeset_table_rev;uniqueIndex:idx_sl_changeset_table_signature"`
	Rev       int64 `gorm:"uniqueIndex:idx_sl_changeset_table_rev"`
	// Signature is generated by the client to recognize its own changeset, it is empty for the changesets generated by the server.
	Signature string `gorm:"uniqueIndex:idx_sl_changeset_table_signature, where:signature <> ''"`
	// ClientID is the connection that submits the changeset, it is empty for the changesets generated by the server.
	ClientID   string
	Operations datatypes.JSON `gorm:"type:jsonb"`
	CreatedAt  time.Time
}

type slChangesets struct {
	*gorm.DB
}

type CreateSLChangesetOptions struct {
	SLTableID  int64
	Rev        int64
	Signature  string
	ClientID   string
	Operations json.RawMessage
}

func (db *slChangesets) Create(ctx context.Context, options CreateSLChangesetOptions) (*SLChangeset, error) {
	changeset := &SLChangeset{
		SLTableID:  options.SLTableID,
		Rev:        options.Rev,
		Signature:  options.Signature,
		ClientID:   options.ClientID,
		Operations: datatypes.JSON(options.Operations),
	}
	if err := db.WithContext(ctx).Create(changeset).Error; err != nil {
		return nil, errors.Wrap(err, "create")
	}
	return changeset, nil
}

var ErrSLChangesetNotFound = errors.New("sl_changeset does not exist")

func (db *slChangesets) GetBySignature(ctx context.Context, tableID int64, signature string) (*SLChangeset, error) {
	var changeset SLChangeset
	if err := db.WithContext(ctx).Model(&SLChangeset{}).Where("sl_table_id = ? AND signature = ?", tableID, signature).First(&changeset).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, ErrSLChangesetNotFound
		}
		return nil, errors.Wrap(err, "get")
	}
	return &changeset, nil
}

func (db *slChangesets) ListSince(ctx context.Context, tableID, rev int64, limit int) ([]*SLChangeset, error) {
	var changesets []*SLChangeset
	if err := db.WithContext(ctx).Model(&SLChangeset{}).Where("sl_table_id = ? AND rev > ?", tableID, rev).Order("rev ASC").Limit(limit).Find(&changesets).Error; err != nil {
		return nil, errors.Wrap(err, "find")
	}
	return changesets, nil
}
