name: Docker
on:
  push:
    branches: [ master ]
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/docker.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Compute image tag name
        run: echo "IMAGE_TAG=$(date -u '+%Y%m%d-%H%M%S')" >> $GITHUB_ENV
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Tencent Cloud container registry
        uses: docker/login-action@v2
        with:
          registry: ccr.ccs.tencentyun.com
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          build-args: |
            GITHUB_SHA=${{ github.sha }}
          tags: |
            ccr.ccs.tencentyun.com/qcloud-image/sayrud-server:${{ env.IMAGE_TAG }}
      - name: Set proxy config
        env:
          HTTP_PROXY: ${{ secrets.HTTP_PROXY }}
          HTTPS_PROXY: ${{ secrets.HTTP_PROXY }}
        run: |
          wget https://github.com/jqlang/jq/releases/download/jq-1.7.1/jq-linux-amd64 -O jq
          chmod +x jq
          sudo sh -c 'ls /etc/docker/daemon.json || echo "{}" > /etc/docker/daemon.json'
          sudo ./jq '. + {"proxies":{"http-proxy": "'"${HTTP_PROXY}"'", "https-proxy": "'"${HTTPS_PROXY}"'"}}' /etc/docker/daemon.json > /tmp/daemon.json.tmp
          sudo mv /tmp/daemon.json.tmp /etc/docker/daemon.json
          sudo systemctl restart docker
      - name: Push image
        run: |
          docker push ccr.ccs.tencentyun.com/qcloud-image/sayrud-server:${{ env.IMAGE_TAG }}

